// Code generated by mockery v2.53.3. DO NOT EDIT.

package exporter

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPClientOption is an autogenerated mock type for the HTTPClientOption type
type MockHTTPClientOption struct {
	mock.Mock
}

type MockHTTPClientOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClientOption) EXPECT() *MockHTTPClientOption_Expecter {
	return &MockHTTPClientOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockHTTPClientOption) Execute(_a0 *http.Client) {
	_m.Called(_a0)
}

// MockHTTPClientOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockHTTPClientOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *http.Client
func (_e *MockHTTPClientOption_Expecter) Execute(_a0 interface{}) *MockHTTPClientOption_Execute_Call {
	return &MockHTTPClientOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockHTTPClientOption_Execute_Call) Run(run func(_a0 *http.Client)) *MockHTTPClientOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Client))
	})
	return _c
}

func (_c *MockHTTPClientOption_Execute_Call) Return() *MockHTTPClientOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPClientOption_Execute_Call) RunAndReturn(run func(*http.Client)) *MockHTTPClientOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockHTTPClientOption creates a new instance of MockHTTPClientOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClientOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClientOption {
	mock := &MockHTTPClientOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
