// Code generated by mockery v2.53.3. DO NOT EDIT.

package exporter

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockApiClient is an autogenerated mock type for the apiClient type
type mockApiClient struct {
	mock.Mock
}

type mockApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockApiClient) EXPECT() *mockApiClient_Expecter {
	return &mockApiClient_Expecter{mock: &_m.Mock}
}

// DoGetRequest provides a mock function with given fields: ctx, path
func (_m *mockApiClient) DoGetRequest(ctx context.Context, path string) ([]byte, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DoGetRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockApiClient_DoGetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoGetRequest'
type mockApiClient_DoGetRequest_Call struct {
	*mock.Call
}

// DoGetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *mockApiClient_Expecter) DoGetRequest(ctx interface{}, path interface{}) *mockApiClient_DoGetRequest_Call {
	return &mockApiClient_DoGetRequest_Call{Call: _e.mock.On("DoGetRequest", ctx, path)}
}

func (_c *mockApiClient_DoGetRequest_Call) Run(run func(ctx context.Context, path string)) *mockApiClient_DoGetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockApiClient_DoGetRequest_Call) Return(result []byte, err error) *mockApiClient_DoGetRequest_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockApiClient_DoGetRequest_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *mockApiClient_DoGetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DoPostRequest provides a mock function with given fields: ctx, path, body
func (_m *mockApiClient) DoPostRequest(ctx context.Context, path string, body io.Reader) ([]byte, error) {
	ret := _m.Called(ctx, path, body)

	if len(ret) == 0 {
		panic("no return value specified for DoPostRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) ([]byte, error)); ok {
		return rf(ctx, path, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) []byte); ok {
		r0 = rf(ctx, path, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader) error); ok {
		r1 = rf(ctx, path, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockApiClient_DoPostRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoPostRequest'
type mockApiClient_DoPostRequest_Call struct {
	*mock.Call
}

// DoPostRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - body io.Reader
func (_e *mockApiClient_Expecter) DoPostRequest(ctx interface{}, path interface{}, body interface{}) *mockApiClient_DoPostRequest_Call {
	return &mockApiClient_DoPostRequest_Call{Call: _e.mock.On("DoPostRequest", ctx, path, body)}
}

func (_c *mockApiClient_DoPostRequest_Call) Run(run func(ctx context.Context, path string, body io.Reader)) *mockApiClient_DoPostRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader))
	})
	return _c
}

func (_c *mockApiClient_DoPostRequest_Call) Return(result []byte, err error) *mockApiClient_DoPostRequest_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockApiClient_DoPostRequest_Call) RunAndReturn(run func(context.Context, string, io.Reader) ([]byte, error)) *mockApiClient_DoPostRequest_Call {
	_c.Call.Return(run)
	return _c
}

// newMockApiClient creates a new instance of mockApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockApiClient {
	mock := &mockApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
