// Code generated by mockery v2.53.3. DO NOT EDIT.

package importer

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v2 "github.com/cloudogu/k8s-dogu-operator/v2/api/v2"
)

// MockDoguInterface is an autogenerated mock type for the DoguInterface type
type MockDoguInterface struct {
	mock.Mock
}

type MockDoguInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguInterface) EXPECT() *MockDoguInterface_Expecter {
	return &MockDoguInterface_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *MockDoguInterface) Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.Dogu, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v2.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*v2.Dogu, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *v2.Dogu); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDoguInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *MockDoguInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *MockDoguInterface_Get_Call {
	return &MockDoguInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *MockDoguInterface_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *MockDoguInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *MockDoguInterface_Get_Call) Return(_a0 *v2.Dogu, _a1 error) *MockDoguInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguInterface_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*v2.Dogu, error)) *MockDoguInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSpecWithRetry provides a mock function with given fields: ctx, dogu, updateFunc, opts
func (_m *MockDoguInterface) UpdateSpecWithRetry(ctx context.Context, dogu *v2.Dogu, updateFunc func(v2.DoguSpec) v2.DoguSpec, opts v1.UpdateOptions) (*v2.Dogu, error) {
	ret := _m.Called(ctx, dogu, updateFunc, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSpecWithRetry")
	}

	var r0 *v2.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, func(v2.DoguSpec) v2.DoguSpec, v1.UpdateOptions) (*v2.Dogu, error)); ok {
		return rf(ctx, dogu, updateFunc, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v2.Dogu, func(v2.DoguSpec) v2.DoguSpec, v1.UpdateOptions) *v2.Dogu); ok {
		r0 = rf(ctx, dogu, updateFunc, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v2.Dogu, func(v2.DoguSpec) v2.DoguSpec, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, dogu, updateFunc, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguInterface_UpdateSpecWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSpecWithRetry'
type MockDoguInterface_UpdateSpecWithRetry_Call struct {
	*mock.Call
}

// UpdateSpecWithRetry is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu *v2.Dogu
//   - updateFunc func(v2.DoguSpec) v2.DoguSpec
//   - opts v1.UpdateOptions
func (_e *MockDoguInterface_Expecter) UpdateSpecWithRetry(ctx interface{}, dogu interface{}, updateFunc interface{}, opts interface{}) *MockDoguInterface_UpdateSpecWithRetry_Call {
	return &MockDoguInterface_UpdateSpecWithRetry_Call{Call: _e.mock.On("UpdateSpecWithRetry", ctx, dogu, updateFunc, opts)}
}

func (_c *MockDoguInterface_UpdateSpecWithRetry_Call) Run(run func(ctx context.Context, dogu *v2.Dogu, updateFunc func(v2.DoguSpec) v2.DoguSpec, opts v1.UpdateOptions)) *MockDoguInterface_UpdateSpecWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v2.Dogu), args[2].(func(v2.DoguSpec) v2.DoguSpec), args[3].(v1.UpdateOptions))
	})
	return _c
}

func (_c *MockDoguInterface_UpdateSpecWithRetry_Call) Return(_a0 *v2.Dogu, _a1 error) *MockDoguInterface_UpdateSpecWithRetry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguInterface_UpdateSpecWithRetry_Call) RunAndReturn(run func(context.Context, *v2.Dogu, func(v2.DoguSpec) v2.DoguSpec, v1.UpdateOptions) (*v2.Dogu, error)) *MockDoguInterface_UpdateSpecWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguInterface creates a new instance of MockDoguInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguInterface {
	mock := &MockDoguInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
