// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDoguVolumeResizer is an autogenerated mock type for the DoguVolumeResizer type
type MockDoguVolumeResizer struct {
	mock.Mock
}

type MockDoguVolumeResizer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguVolumeResizer) EXPECT() *MockDoguVolumeResizer_Expecter {
	return &MockDoguVolumeResizer_Expecter{mock: &_m.Mock}
}

// ResizeDogusIfNeeded provides a mock function with given fields: ctx, exporterDogus, importerDogus
func (_m *MockDoguVolumeResizer) ResizeDogusIfNeeded(ctx context.Context, exporterDogus []Dogu, importerDogus []Dogu) error {
	ret := _m.Called(ctx, exporterDogus, importerDogus)

	if len(ret) == 0 {
		panic("no return value specified for ResizeDogusIfNeeded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []Dogu, []Dogu) error); ok {
		r0 = rf(ctx, exporterDogus, importerDogus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguVolumeResizer_ResizeDogusIfNeeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeDogusIfNeeded'
type MockDoguVolumeResizer_ResizeDogusIfNeeded_Call struct {
	*mock.Call
}

// ResizeDogusIfNeeded is a helper method to define mock.On call
//   - ctx context.Context
//   - exporterDogus []Dogu
//   - importerDogus []Dogu
func (_e *MockDoguVolumeResizer_Expecter) ResizeDogusIfNeeded(ctx interface{}, exporterDogus interface{}, importerDogus interface{}) *MockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	return &MockDoguVolumeResizer_ResizeDogusIfNeeded_Call{Call: _e.mock.On("ResizeDogusIfNeeded", ctx, exporterDogus, importerDogus)}
}

func (_c *MockDoguVolumeResizer_ResizeDogusIfNeeded_Call) Run(run func(ctx context.Context, exporterDogus []Dogu, importerDogus []Dogu)) *MockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]Dogu), args[2].([]Dogu))
	})
	return _c
}

func (_c *MockDoguVolumeResizer_ResizeDogusIfNeeded_Call) Return(_a0 error) *MockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguVolumeResizer_ResizeDogusIfNeeded_Call) RunAndReturn(run func(context.Context, []Dogu, []Dogu) error) *MockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguVolumeResizer creates a new instance of MockDoguVolumeResizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguVolumeResizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguVolumeResizer {
	mock := &MockDoguVolumeResizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
