// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDoguStarter is an autogenerated mock type for the DoguStarter type
type MockDoguStarter struct {
	mock.Mock
}

type MockDoguStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguStarter) EXPECT() *MockDoguStarter_Expecter {
	return &MockDoguStarter_Expecter{mock: &_m.Mock}
}

// StartAll provides a mock function with given fields: ctx
func (_m *MockDoguStarter) StartAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguStarter_StartAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAll'
type MockDoguStarter_StartAll_Call struct {
	*mock.Call
}

// StartAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDoguStarter_Expecter) StartAll(ctx interface{}) *MockDoguStarter_StartAll_Call {
	return &MockDoguStarter_StartAll_Call{Call: _e.mock.On("StartAll", ctx)}
}

func (_c *MockDoguStarter_StartAll_Call) Run(run func(ctx context.Context)) *MockDoguStarter_StartAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDoguStarter_StartAll_Call) Return(_a0 error) *MockDoguStarter_StartAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguStarter_StartAll_Call) RunAndReturn(run func(context.Context) error) *MockDoguStarter_StartAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguStarter creates a new instance of MockDoguStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguStarter {
	mock := &MockDoguStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
