// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "k8s.io/api/batch/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockJobClient is an autogenerated mock type for the jobClient type
type mockJobClient struct {
	mock.Mock
}

type mockJobClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockJobClient) EXPECT() *mockJobClient_Expecter {
	return &mockJobClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, job, opts
func (_m *mockJobClient) Create(ctx context.Context, job *v1.Job, opts metav1.CreateOptions) (*v1.Job, error) {
	ret := _m.Called(ctx, job, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Job, metav1.CreateOptions) (*v1.Job, error)); ok {
		return rf(ctx, job, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Job, metav1.CreateOptions) *v1.Job); ok {
		r0 = rf(ctx, job, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Job, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, job, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockJobClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockJobClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - job *v1.Job
//   - opts metav1.CreateOptions
func (_e *mockJobClient_Expecter) Create(ctx interface{}, job interface{}, opts interface{}) *mockJobClient_Create_Call {
	return &mockJobClient_Create_Call{Call: _e.mock.On("Create", ctx, job, opts)}
}

func (_c *mockJobClient_Create_Call) Run(run func(ctx context.Context, job *v1.Job, opts metav1.CreateOptions)) *mockJobClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Job), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockJobClient_Create_Call) Return(_a0 *v1.Job, _a1 error) *mockJobClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockJobClient_Create_Call) RunAndReturn(run func(context.Context, *v1.Job, metav1.CreateOptions) (*v1.Job, error)) *mockJobClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockJobClient) List(ctx context.Context, opts metav1.ListOptions) (*v1.JobList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.JobList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*v1.JobList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *v1.JobList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.JobList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockJobClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockJobClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockJobClient_Expecter) List(ctx interface{}, opts interface{}) *mockJobClient_List_Call {
	return &mockJobClient_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockJobClient_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockJobClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockJobClient_List_Call) Return(_a0 *v1.JobList, _a1 error) *mockJobClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockJobClient_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*v1.JobList, error)) *mockJobClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockJobClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockJobClient_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockJobClient_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockJobClient_Expecter) Watch(ctx interface{}, opts interface{}) *mockJobClient_Watch_Call {
	return &mockJobClient_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockJobClient_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockJobClient_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockJobClient_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockJobClient_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockJobClient_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *mockJobClient_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockJobClient creates a new instance of mockJobClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockJobClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockJobClient {
	mock := &mockJobClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
