// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockExportModeClient is an autogenerated mock type for the exportModeClient type
type mockExportModeClient struct {
	mock.Mock
}

type mockExportModeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockExportModeClient) EXPECT() *mockExportModeClient_Expecter {
	return &mockExportModeClient_Expecter{mock: &_m.Mock}
}

// GetExportMode provides a mock function with given fields: ctx
func (_m *mockExportModeClient) GetExportMode(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExportMode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExportModeClient_GetExportMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportMode'
type mockExportModeClient_GetExportMode_Call struct {
	*mock.Call
}

// GetExportMode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockExportModeClient_Expecter) GetExportMode(ctx interface{}) *mockExportModeClient_GetExportMode_Call {
	return &mockExportModeClient_GetExportMode_Call{Call: _e.mock.On("GetExportMode", ctx)}
}

func (_c *mockExportModeClient_GetExportMode_Call) Run(run func(ctx context.Context)) *mockExportModeClient_GetExportMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockExportModeClient_GetExportMode_Call) Return(isActive bool, err error) *mockExportModeClient_GetExportMode_Call {
	_c.Call.Return(isActive, err)
	return _c
}

func (_c *mockExportModeClient_GetExportMode_Call) RunAndReturn(run func(context.Context) (bool, error)) *mockExportModeClient_GetExportMode_Call {
	_c.Call.Return(run)
	return _c
}

// newMockExportModeClient creates a new instance of mockExportModeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockExportModeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockExportModeClient {
	mock := &mockExportModeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
