// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMaintenanceModeHandler is an autogenerated mock type for the MaintenanceModeHandler type
type MockMaintenanceModeHandler struct {
	mock.Mock
}

type MockMaintenanceModeHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaintenanceModeHandler) EXPECT() *MockMaintenanceModeHandler_Expecter {
	return &MockMaintenanceModeHandler_Expecter{mock: &_m.Mock}
}

// Disable provides a mock function with given fields: ctx
func (_m *MockMaintenanceModeHandler) Disable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaintenanceModeHandler_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type MockMaintenanceModeHandler_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMaintenanceModeHandler_Expecter) Disable(ctx interface{}) *MockMaintenanceModeHandler_Disable_Call {
	return &MockMaintenanceModeHandler_Disable_Call{Call: _e.mock.On("Disable", ctx)}
}

func (_c *MockMaintenanceModeHandler_Disable_Call) Run(run func(ctx context.Context)) *MockMaintenanceModeHandler_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMaintenanceModeHandler_Disable_Call) Return(_a0 error) *MockMaintenanceModeHandler_Disable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaintenanceModeHandler_Disable_Call) RunAndReturn(run func(context.Context) error) *MockMaintenanceModeHandler_Disable_Call {
	_c.Call.Return(run)
	return _c
}

// Enable provides a mock function with given fields: ctx
func (_m *MockMaintenanceModeHandler) Enable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Enable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMaintenanceModeHandler_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type MockMaintenanceModeHandler_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMaintenanceModeHandler_Expecter) Enable(ctx interface{}) *MockMaintenanceModeHandler_Enable_Call {
	return &MockMaintenanceModeHandler_Enable_Call{Call: _e.mock.On("Enable", ctx)}
}

func (_c *MockMaintenanceModeHandler_Enable_Call) Run(run func(ctx context.Context)) *MockMaintenanceModeHandler_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMaintenanceModeHandler_Enable_Call) Return(_a0 error) *MockMaintenanceModeHandler_Enable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMaintenanceModeHandler_Enable_Call) RunAndReturn(run func(context.Context) error) *MockMaintenanceModeHandler_Enable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMaintenanceModeHandler creates a new instance of MockMaintenanceModeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaintenanceModeHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaintenanceModeHandler {
	mock := &MockMaintenanceModeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
