// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockStreamer is an autogenerated mock type for the streamer type
type mockStreamer struct {
	mock.Mock
}

type mockStreamer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStreamer) EXPECT() *mockStreamer_Expecter {
	return &mockStreamer_Expecter{mock: &_m.Mock}
}

// Stream provides a mock function with given fields: ctx
func (_m *mockStreamer) Stream(ctx context.Context) (io.ReadCloser, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (io.ReadCloser, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) io.ReadCloser); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockStreamer_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type mockStreamer_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockStreamer_Expecter) Stream(ctx interface{}) *mockStreamer_Stream_Call {
	return &mockStreamer_Stream_Call{Call: _e.mock.On("Stream", ctx)}
}

func (_c *mockStreamer_Stream_Call) Run(run func(ctx context.Context)) *mockStreamer_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockStreamer_Stream_Call) Return(_a0 io.ReadCloser, _a1 error) *mockStreamer_Stream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockStreamer_Stream_Call) RunAndReturn(run func(context.Context) (io.ReadCloser, error)) *mockStreamer_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStreamer creates a new instance of mockStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStreamer {
	mock := &mockStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
