// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBlueprintStopper is an autogenerated mock type for the BlueprintStopper type
type MockBlueprintStopper struct {
	mock.Mock
}

type MockBlueprintStopper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlueprintStopper) EXPECT() *MockBlueprintStopper_Expecter {
	return &MockBlueprintStopper_Expecter{mock: &_m.Mock}
}

// StopBlueprint provides a mock function with given fields: ctx
func (_m *MockBlueprintStopper) StopBlueprint(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StopBlueprint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlueprintStopper_StopBlueprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopBlueprint'
type MockBlueprintStopper_StopBlueprint_Call struct {
	*mock.Call
}

// StopBlueprint is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlueprintStopper_Expecter) StopBlueprint(ctx interface{}) *MockBlueprintStopper_StopBlueprint_Call {
	return &MockBlueprintStopper_StopBlueprint_Call{Call: _e.mock.On("StopBlueprint", ctx)}
}

func (_c *MockBlueprintStopper_StopBlueprint_Call) Run(run func(ctx context.Context)) *MockBlueprintStopper_StopBlueprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBlueprintStopper_StopBlueprint_Call) Return(_a0 error) *MockBlueprintStopper_StopBlueprint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlueprintStopper_StopBlueprint_Call) RunAndReturn(run func(context.Context) error) *MockBlueprintStopper_StopBlueprint_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlueprintStopper creates a new instance of MockBlueprintStopper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlueprintStopper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlueprintStopper {
	mock := &MockBlueprintStopper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
