// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	rest "k8s.io/client-go/rest"

	v1 "k8s.io/api/core/v1"
)

// mockPodClient is an autogenerated mock type for the podClient type
type mockPodClient struct {
	mock.Mock
}

type mockPodClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPodClient) EXPECT() *mockPodClient_Expecter {
	return &mockPodClient_Expecter{mock: &_m.Mock}
}

// GetLogs provides a mock function with given fields: name, opts
func (_m *mockPodClient) GetLogs(name string, opts *v1.PodLogOptions) *rest.Request {
	ret := _m.Called(name, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 *rest.Request
	if rf, ok := ret.Get(0).(func(string, *v1.PodLogOptions) *rest.Request); ok {
		r0 = rf(name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}

	return r0
}

// mockPodClient_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type mockPodClient_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - name string
//   - opts *v1.PodLogOptions
func (_e *mockPodClient_Expecter) GetLogs(name interface{}, opts interface{}) *mockPodClient_GetLogs_Call {
	return &mockPodClient_GetLogs_Call{Call: _e.mock.On("GetLogs", name, opts)}
}

func (_c *mockPodClient_GetLogs_Call) Run(run func(name string, opts *v1.PodLogOptions)) *mockPodClient_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.PodLogOptions))
	})
	return _c
}

func (_c *mockPodClient_GetLogs_Call) Return(_a0 *rest.Request) *mockPodClient_GetLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockPodClient_GetLogs_Call) RunAndReturn(run func(string, *v1.PodLogOptions) *rest.Request) *mockPodClient_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockPodClient) List(ctx context.Context, opts metav1.ListOptions) (*v1.PodList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.PodList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*v1.PodList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *v1.PodList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PodList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPodClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockPodClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockPodClient_Expecter) List(ctx interface{}, opts interface{}) *mockPodClient_List_Call {
	return &mockPodClient_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockPodClient_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockPodClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockPodClient_List_Call) Return(_a0 *v1.PodList, _a1 error) *mockPodClient_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPodClient_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*v1.PodList, error)) *mockPodClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPodClient creates a new instance of mockPodClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPodClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPodClient {
	mock := &mockPodClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
