// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSystemInfoValidator is an autogenerated mock type for the SystemInfoValidator type
type MockSystemInfoValidator struct {
	mock.Mock
}

type MockSystemInfoValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemInfoValidator) EXPECT() *MockSystemInfoValidator_Expecter {
	return &MockSystemInfoValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: ctx
func (_m *MockSystemInfoValidator) Validate(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemInfoValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockSystemInfoValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemInfoValidator_Expecter) Validate(ctx interface{}) *MockSystemInfoValidator_Validate_Call {
	return &MockSystemInfoValidator_Validate_Call{Call: _e.mock.On("Validate", ctx)}
}

func (_c *MockSystemInfoValidator_Validate_Call) Run(run func(ctx context.Context)) *MockSystemInfoValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemInfoValidator_Validate_Call) Return(_a0 error) *MockSystemInfoValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemInfoValidator_Validate_Call) RunAndReturn(run func(context.Context) error) *MockSystemInfoValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemInfoValidator creates a new instance of MockSystemInfoValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemInfoValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemInfoValidator {
	mock := &MockSystemInfoValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
