// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
	rest "k8s.io/client-go/rest"
)

// mockPodLogGetter is an autogenerated mock type for the podLogGetter type
type mockPodLogGetter struct {
	mock.Mock
}

type mockPodLogGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPodLogGetter) EXPECT() *mockPodLogGetter_Expecter {
	return &mockPodLogGetter_Expecter{mock: &_m.Mock}
}

// GetLogs provides a mock function with given fields: name, opts
func (_m *mockPodLogGetter) GetLogs(name string, opts *v1.PodLogOptions) *rest.Request {
	ret := _m.Called(name, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 *rest.Request
	if rf, ok := ret.Get(0).(func(string, *v1.PodLogOptions) *rest.Request); ok {
		r0 = rf(name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Request)
		}
	}

	return r0
}

// mockPodLogGetter_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type mockPodLogGetter_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - name string
//   - opts *v1.PodLogOptions
func (_e *mockPodLogGetter_Expecter) GetLogs(name interface{}, opts interface{}) *mockPodLogGetter_GetLogs_Call {
	return &mockPodLogGetter_GetLogs_Call{Call: _e.mock.On("GetLogs", name, opts)}
}

func (_c *mockPodLogGetter_GetLogs_Call) Run(run func(name string, opts *v1.PodLogOptions)) *mockPodLogGetter_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.PodLogOptions))
	})
	return _c
}

func (_c *mockPodLogGetter_GetLogs_Call) Return(_a0 *rest.Request) *mockPodLogGetter_GetLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockPodLogGetter_GetLogs_Call) RunAndReturn(run func(string, *v1.PodLogOptions) *rest.Request) *mockPodLogGetter_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPodLogGetter creates a new instance of mockPodLogGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPodLogGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPodLogGetter {
	mock := &mockPodLogGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
