// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockPodLister is an autogenerated mock type for the podLister type
type mockPodLister struct {
	mock.Mock
}

type mockPodLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPodLister) EXPECT() *mockPodLister_Expecter {
	return &mockPodLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockPodLister) List(ctx context.Context, opts v1.ListOptions) (*corev1.PodList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *corev1.PodList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*corev1.PodList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *corev1.PodList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PodList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPodLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockPodLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockPodLister_Expecter) List(ctx interface{}, opts interface{}) *mockPodLister_List_Call {
	return &mockPodLister_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockPodLister_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockPodLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockPodLister_List_Call) Return(_a0 *corev1.PodList, _a1 error) *mockPodLister_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPodLister_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*corev1.PodList, error)) *mockPodLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPodLister creates a new instance of mockPodLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPodLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPodLister {
	mock := &mockPodLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
