// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDoguStopper is an autogenerated mock type for the DoguStopper type
type MockDoguStopper struct {
	mock.Mock
}

type MockDoguStopper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguStopper) EXPECT() *MockDoguStopper_Expecter {
	return &MockDoguStopper_Expecter{mock: &_m.Mock}
}

// StopAll provides a mock function with given fields: ctx
func (_m *MockDoguStopper) StopAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StopAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguStopper_StopAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAll'
type MockDoguStopper_StopAll_Call struct {
	*mock.Call
}

// StopAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDoguStopper_Expecter) StopAll(ctx interface{}) *MockDoguStopper_StopAll_Call {
	return &MockDoguStopper_StopAll_Call{Call: _e.mock.On("StopAll", ctx)}
}

func (_c *MockDoguStopper_StopAll_Call) Run(run func(ctx context.Context)) *MockDoguStopper_StopAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDoguStopper_StopAll_Call) Return(_a0 error) *MockDoguStopper_StopAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguStopper_StopAll_Call) RunAndReturn(run func(context.Context) error) *MockDoguStopper_StopAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguStopper creates a new instance of MockDoguStopper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguStopper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguStopper {
	mock := &MockDoguStopper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
