// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockJobRunner is an autogenerated mock type for the JobRunner type
type MockJobRunner struct {
	mock.Mock
}

type MockJobRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRunner) EXPECT() *MockJobRunner_Expecter {
	return &MockJobRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx
func (_m *MockJobRunner) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockJobRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJobRunner_Expecter) Run(ctx interface{}) *MockJobRunner_Run_Call {
	return &MockJobRunner_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockJobRunner_Run_Call) Run(run func(ctx context.Context)) *MockJobRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockJobRunner_Run_Call) Return(_a0 error) *MockJobRunner_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRunner_Run_Call) RunAndReturn(run func(context.Context) error) *MockJobRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobRunner creates a new instance of MockJobRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRunner {
	mock := &MockJobRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
