// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import mock "github.com/stretchr/testify/mock"

// MockLogInitializerFunc is an autogenerated mock type for the LogInitializerFunc type
type MockLogInitializerFunc struct {
	mock.Mock
}

type MockLogInitializerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogInitializerFunc) EXPECT() *MockLogInitializerFunc_Expecter {
	return &MockLogInitializerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockLogInitializerFunc) Execute() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLogInitializerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockLogInitializerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockLogInitializerFunc_Expecter) Execute() *MockLogInitializerFunc_Execute_Call {
	return &MockLogInitializerFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockLogInitializerFunc_Execute_Call) Run(run func()) *MockLogInitializerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogInitializerFunc_Execute_Call) Return(_a0 error) *MockLogInitializerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogInitializerFunc_Execute_Call) RunAndReturn(run func() error) *MockLogInitializerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogInitializerFunc creates a new instance of MockLogInitializerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogInitializerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogInitializerFunc {
	mock := &MockLogInitializerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
