// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
)

// mockGetStreamerFunc is an autogenerated mock type for the getStreamerFunc type
type mockGetStreamerFunc struct {
	mock.Mock
}

type mockGetStreamerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGetStreamerFunc) EXPECT() *mockGetStreamerFunc_Expecter {
	return &mockGetStreamerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: jobName, options
func (_m *mockGetStreamerFunc) Execute(jobName string, options *v1.PodLogOptions) (streamer, error) {
	ret := _m.Called(jobName, options)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 streamer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *v1.PodLogOptions) (streamer, error)); ok {
		return rf(jobName, options)
	}
	if rf, ok := ret.Get(0).(func(string, *v1.PodLogOptions) streamer); ok {
		r0 = rf(jobName, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(streamer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *v1.PodLogOptions) error); ok {
		r1 = rf(jobName, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockGetStreamerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockGetStreamerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - jobName string
//   - options *v1.PodLogOptions
func (_e *mockGetStreamerFunc_Expecter) Execute(jobName interface{}, options interface{}) *mockGetStreamerFunc_Execute_Call {
	return &mockGetStreamerFunc_Execute_Call{Call: _e.mock.On("Execute", jobName, options)}
}

func (_c *mockGetStreamerFunc_Execute_Call) Run(run func(jobName string, options *v1.PodLogOptions)) *mockGetStreamerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*v1.PodLogOptions))
	})
	return _c
}

func (_c *mockGetStreamerFunc_Execute_Call) Return(_a0 streamer, _a1 error) *mockGetStreamerFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockGetStreamerFunc_Execute_Call) RunAndReturn(run func(string, *v1.PodLogOptions) (streamer, error)) *mockGetStreamerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGetStreamerFunc creates a new instance of mockGetStreamerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGetStreamerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGetStreamerFunc {
	mock := &mockGetStreamerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
