// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import mock "github.com/stretchr/testify/mock"

// MockLogInitializer is an autogenerated mock type for the LogInitializer type
type MockLogInitializer struct {
	mock.Mock
}

type MockLogInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogInitializer) EXPECT() *MockLogInitializer_Expecter {
	return &MockLogInitializer_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function with no fields
func (_m *MockLogInitializer) Initialize() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLogInitializer_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type MockLogInitializer_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
func (_e *MockLogInitializer_Expecter) Initialize() *MockLogInitializer_Initialize_Call {
	return &MockLogInitializer_Initialize_Call{Call: _e.mock.On("Initialize")}
}

func (_c *MockLogInitializer_Initialize_Call) Run(run func()) *MockLogInitializer_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogInitializer_Initialize_Call) Return(_a0 error) *MockLogInitializer_Initialize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogInitializer_Initialize_Call) RunAndReturn(run func() error) *MockLogInitializer_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogInitializer creates a new instance of MockLogInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogInitializer {
	mock := &MockLogInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
