// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSystemInfoProvider is an autogenerated mock type for the SystemInfoProvider type
type MockSystemInfoProvider struct {
	mock.Mock
}

type MockSystemInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemInfoProvider) EXPECT() *MockSystemInfoProvider_Expecter {
	return &MockSystemInfoProvider_Expecter{mock: &_m.Mock}
}

// GetExporterSystemInfo provides a mock function with given fields: ctx
func (_m *MockSystemInfoProvider) GetExporterSystemInfo(ctx context.Context) (*SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExporterSystemInfo")
	}

	var r0 *SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SystemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemInfoProvider_GetExporterSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExporterSystemInfo'
type MockSystemInfoProvider_GetExporterSystemInfo_Call struct {
	*mock.Call
}

// GetExporterSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemInfoProvider_Expecter) GetExporterSystemInfo(ctx interface{}) *MockSystemInfoProvider_GetExporterSystemInfo_Call {
	return &MockSystemInfoProvider_GetExporterSystemInfo_Call{Call: _e.mock.On("GetExporterSystemInfo", ctx)}
}

func (_c *MockSystemInfoProvider_GetExporterSystemInfo_Call) Run(run func(ctx context.Context)) *MockSystemInfoProvider_GetExporterSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemInfoProvider_GetExporterSystemInfo_Call) Return(_a0 *SystemInfo, _a1 error) *MockSystemInfoProvider_GetExporterSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemInfoProvider_GetExporterSystemInfo_Call) RunAndReturn(run func(context.Context) (*SystemInfo, error)) *MockSystemInfoProvider_GetExporterSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetImporterSystemInfo provides a mock function with given fields: ctx
func (_m *MockSystemInfoProvider) GetImporterSystemInfo(ctx context.Context) (*SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImporterSystemInfo")
	}

	var r0 *SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SystemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemInfoProvider_GetImporterSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImporterSystemInfo'
type MockSystemInfoProvider_GetImporterSystemInfo_Call struct {
	*mock.Call
}

// GetImporterSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemInfoProvider_Expecter) GetImporterSystemInfo(ctx interface{}) *MockSystemInfoProvider_GetImporterSystemInfo_Call {
	return &MockSystemInfoProvider_GetImporterSystemInfo_Call{Call: _e.mock.On("GetImporterSystemInfo", ctx)}
}

func (_c *MockSystemInfoProvider_GetImporterSystemInfo_Call) Run(run func(ctx context.Context)) *MockSystemInfoProvider_GetImporterSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemInfoProvider_GetImporterSystemInfo_Call) Return(_a0 *SystemInfo, _a1 error) *MockSystemInfoProvider_GetImporterSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemInfoProvider_GetImporterSystemInfo_Call) RunAndReturn(run func(context.Context) (*SystemInfo, error)) *MockSystemInfoProvider_GetImporterSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemInfoProvider creates a new instance of MockSystemInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemInfoProvider {
	mock := &MockSystemInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
