// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	watch "k8s.io/apimachinery/pkg/watch"
)

// mockGetWatcherFunc is an autogenerated mock type for the getWatcherFunc type
type mockGetWatcherFunc struct {
	mock.Mock
}

type mockGetWatcherFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGetWatcherFunc) EXPECT() *mockGetWatcherFunc_Expecter {
	return &mockGetWatcherFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, resourceVersion
func (_m *mockGetWatcherFunc) Execute(ctx context.Context, resourceVersion string) (watch.Interface, error) {
	ret := _m.Called(ctx, resourceVersion)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (watch.Interface, error)); ok {
		return rf(ctx, resourceVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) watch.Interface); ok {
		r0 = rf(ctx, resourceVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resourceVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockGetWatcherFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockGetWatcherFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceVersion string
func (_e *mockGetWatcherFunc_Expecter) Execute(ctx interface{}, resourceVersion interface{}) *mockGetWatcherFunc_Execute_Call {
	return &mockGetWatcherFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, resourceVersion)}
}

func (_c *mockGetWatcherFunc_Execute_Call) Run(run func(ctx context.Context, resourceVersion string)) *mockGetWatcherFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockGetWatcherFunc_Execute_Call) Return(_a0 watch.Interface, _a1 error) *mockGetWatcherFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockGetWatcherFunc_Execute_Call) RunAndReturn(run func(context.Context, string) (watch.Interface, error)) *mockGetWatcherFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGetWatcherFunc creates a new instance of mockGetWatcherFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGetWatcherFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGetWatcherFunc {
	mock := &mockGetWatcherFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
