// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockPvcClient is an autogenerated mock type for the pvcClient type
type mockPvcClient struct {
	mock.Mock
}

type mockPvcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPvcClient) EXPECT() *mockPvcClient_Expecter {
	return &mockPvcClient_Expecter{mock: &_m.Mock}
}

// GetDoguVolumes provides a mock function with given fields: ctx
func (_m *mockPvcClient) GetDoguVolumes(ctx context.Context) ([]doguPVC, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDoguVolumes")
	}

	var r0 []doguPVC
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]doguPVC, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []doguPVC); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]doguPVC)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcClient_GetDoguVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDoguVolumes'
type mockPvcClient_GetDoguVolumes_Call struct {
	*mock.Call
}

// GetDoguVolumes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockPvcClient_Expecter) GetDoguVolumes(ctx interface{}) *mockPvcClient_GetDoguVolumes_Call {
	return &mockPvcClient_GetDoguVolumes_Call{Call: _e.mock.On("GetDoguVolumes", ctx)}
}

func (_c *mockPvcClient_GetDoguVolumes_Call) Run(run func(ctx context.Context)) *mockPvcClient_GetDoguVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockPvcClient_GetDoguVolumes_Call) Return(_a0 []doguPVC, _a1 error) *mockPvcClient_GetDoguVolumes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcClient_GetDoguVolumes_Call) RunAndReturn(run func(context.Context) ([]doguPVC, error)) *mockPvcClient_GetDoguVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPvcClient creates a new instance of mockPvcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPvcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPvcClient {
	mock := &mockPvcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
