// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockMailSender is an autogenerated mock type for the MailSender type
type MockMailSender struct {
	mock.Mock
}

type MockMailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailSender) EXPECT() *MockMailSender_Expecter {
	return &MockMailSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: isFinal, migrationResult, source, target, startTime, endTime
func (_m *MockMailSender) Send(isFinal bool, migrationResult error, source string, target string, startTime time.Time, endTime time.Time) error {
	ret := _m.Called(isFinal, migrationResult, source, target, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool, error, string, string, time.Time, time.Time) error); ok {
		r0 = rf(isFinal, migrationResult, source, target, startTime, endTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMailSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - isFinal bool
//   - migrationResult error
//   - source string
//   - target string
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockMailSender_Expecter) Send(isFinal interface{}, migrationResult interface{}, source interface{}, target interface{}, startTime interface{}, endTime interface{}) *MockMailSender_Send_Call {
	return &MockMailSender_Send_Call{Call: _e.mock.On("Send", isFinal, migrationResult, source, target, startTime, endTime)}
}

func (_c *MockMailSender_Send_Call) Run(run func(isFinal bool, migrationResult error, source string, target string, startTime time.Time, endTime time.Time)) *MockMailSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool), args[1].(error), args[2].(string), args[3].(string), args[4].(time.Time), args[5].(time.Time))
	})
	return _c
}

func (_c *MockMailSender_Send_Call) Return(_a0 error) *MockMailSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailSender_Send_Call) RunAndReturn(run func(bool, error, string, string, time.Time, time.Time) error) *MockMailSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailSender creates a new instance of MockMailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailSender {
	mock := &MockMailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
