// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockLogWriter is an autogenerated mock type for the LogWriter type
type MockLogWriter struct {
	mock.Mock
}

type MockLogWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogWriter) EXPECT() *MockLogWriter_Expecter {
	return &MockLogWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: _a0
func (_m *MockLogWriter) Write(_a0 io.ReadCloser) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.ReadCloser) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLogWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockLogWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - _a0 io.ReadCloser
func (_e *MockLogWriter_Expecter) Write(_a0 interface{}) *MockLogWriter_Write_Call {
	return &MockLogWriter_Write_Call{Call: _e.mock.On("Write", _a0)}
}

func (_c *MockLogWriter_Write_Call) Run(run func(_a0 io.ReadCloser)) *MockLogWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.ReadCloser))
	})
	return _c
}

func (_c *MockLogWriter_Write_Call) Return(_a0 error) *MockLogWriter_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLogWriter_Write_Call) RunAndReturn(run func(io.ReadCloser) error) *MockLogWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogWriter creates a new instance of MockLogWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogWriter {
	mock := &MockLogWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
