// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/batch/v1"
)

// mockJobCreator is an autogenerated mock type for the jobCreator type
type mockJobCreator struct {
	mock.Mock
}

type mockJobCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockJobCreator) EXPECT() *mockJobCreator_Expecter {
	return &mockJobCreator_Expecter{mock: &_m.Mock}
}

// createImportJob provides a mock function with given fields: ctx
func (_m *mockJobCreator) createImportJob(ctx context.Context) (*v1.Job, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for createImportJob")
	}

	var r0 *v1.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*v1.Job, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *v1.Job); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockJobCreator_createImportJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createImportJob'
type mockJobCreator_createImportJob_Call struct {
	*mock.Call
}

// createImportJob is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockJobCreator_Expecter) createImportJob(ctx interface{}) *mockJobCreator_createImportJob_Call {
	return &mockJobCreator_createImportJob_Call{Call: _e.mock.On("createImportJob", ctx)}
}

func (_c *mockJobCreator_createImportJob_Call) Run(run func(ctx context.Context)) *mockJobCreator_createImportJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockJobCreator_createImportJob_Call) Return(_a0 *v1.Job, _a1 error) *mockJobCreator_createImportJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockJobCreator_createImportJob_Call) RunAndReturn(run func(context.Context) (*v1.Job, error)) *mockJobCreator_createImportJob_Call {
	_c.Call.Return(run)
	return _c
}

// newMockJobCreator creates a new instance of mockJobCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockJobCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockJobCreator {
	mock := &mockJobCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
