// Code generated by mockery v2.53.3. DO NOT EDIT.

package migration

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockJobRunner is an autogenerated mock type for the JobRunner type
type MockJobRunner struct {
	mock.Mock
}

type MockJobRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRunner) EXPECT() *MockJobRunner_Expecter {
	return &MockJobRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *MockJobRunner) Run() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockJobRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockJobRunner_Expecter) Run() *MockJobRunner_Run_Call {
	return &MockJobRunner_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockJobRunner_Run_Call) Run(run func()) *MockJobRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobRunner_Run_Call) Return(_a0 io.ReadCloser, _a1 error) *MockJobRunner_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRunner_Run_Call) RunAndReturn(run func() (io.ReadCloser, error)) *MockJobRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobRunner creates a new instance of MockJobRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRunner {
	mock := &MockJobRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
