// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguStarter is an autogenerated mock type for the doguStarter type
type mockDoguStarter struct {
	mock.Mock
}

type mockDoguStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguStarter) EXPECT() *mockDoguStarter_Expecter {
	return &mockDoguStarter_Expecter{mock: &_m.Mock}
}

// StartDogu provides a mock function with given fields: ctx, dogu
func (_m *mockDoguStarter) StartDogu(ctx context.Context, dogu exporter.Dogu) error {
	ret := _m.Called(ctx, dogu)

	if len(ret) == 0 {
		panic("no return value specified for StartDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, exporter.Dogu) error); ok {
		r0 = rf(ctx, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguStarter_StartDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartDogu'
type mockDoguStarter_StartDogu_Call struct {
	*mock.Call
}

// StartDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu exporter.Dogu
func (_e *mockDoguStarter_Expecter) StartDogu(ctx interface{}, dogu interface{}) *mockDoguStarter_StartDogu_Call {
	return &mockDoguStarter_StartDogu_Call{Call: _e.mock.On("StartDogu", ctx, dogu)}
}

func (_c *mockDoguStarter_StartDogu_Call) Run(run func(ctx context.Context, dogu exporter.Dogu)) *mockDoguStarter_StartDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exporter.Dogu))
	})
	return _c
}

func (_c *mockDoguStarter_StartDogu_Call) Return(_a0 error) *mockDoguStarter_StartDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguStarter_StartDogu_Call) RunAndReturn(run func(context.Context, exporter.Dogu) error) *mockDoguStarter_StartDogu_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguStarter creates a new instance of mockDoguStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguStarter {
	mock := &mockDoguStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
