// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "k8s.io/api/batch/v1"
)

// mockJobClient is an autogenerated mock type for the jobClient type
type mockJobClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, job, opts
func (_m *mockJobClient) Create(ctx context.Context, job *v1.Job, opts metav1.CreateOptions) (*v1.Job, error) {
	ret := _m.Called(ctx, job, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Job, metav1.CreateOptions) (*v1.Job, error)); ok {
		return rf(ctx, job, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Job, metav1.CreateOptions) *v1.Job); ok {
		r0 = rf(ctx, job, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Job, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, job, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockJobClient creates a new instance of mockJobClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockJobClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockJobClient {
	mock := &mockJobClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
