// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockExporterApiClient is an autogenerated mock type for the exporterApiClient type
type mockExporterApiClient struct {
	mock.Mock
}

type mockExporterApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockExporterApiClient) EXPECT() *mockExporterApiClient_Expecter {
	return &mockExporterApiClient_Expecter{mock: &_m.Mock}
}

// DoGetRequest provides a mock function with given fields: ctx, url
func (_m *mockExporterApiClient) DoGetRequest(ctx context.Context, url string) ([]byte, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for DoGetRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExporterApiClient_DoGetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoGetRequest'
type mockExporterApiClient_DoGetRequest_Call struct {
	*mock.Call
}

// DoGetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *mockExporterApiClient_Expecter) DoGetRequest(ctx interface{}, url interface{}) *mockExporterApiClient_DoGetRequest_Call {
	return &mockExporterApiClient_DoGetRequest_Call{Call: _e.mock.On("DoGetRequest", ctx, url)}
}

func (_c *mockExporterApiClient_DoGetRequest_Call) Run(run func(ctx context.Context, url string)) *mockExporterApiClient_DoGetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockExporterApiClient_DoGetRequest_Call) Return(_a0 []byte, _a1 error) *mockExporterApiClient_DoGetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExporterApiClient_DoGetRequest_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *mockExporterApiClient_DoGetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DoPostRequest provides a mock function with given fields: ctx, exporterUrl, body, pathParams
func (_m *mockExporterApiClient) DoPostRequest(ctx context.Context, exporterUrl string, body io.Reader, pathParams []string) ([]byte, error) {
	ret := _m.Called(ctx, exporterUrl, body, pathParams)

	if len(ret) == 0 {
		panic("no return value specified for DoPostRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, []string) ([]byte, error)); ok {
		return rf(ctx, exporterUrl, body, pathParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, []string) []byte); ok {
		r0 = rf(ctx, exporterUrl, body, pathParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, []string) error); ok {
		r1 = rf(ctx, exporterUrl, body, pathParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExporterApiClient_DoPostRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoPostRequest'
type mockExporterApiClient_DoPostRequest_Call struct {
	*mock.Call
}

// DoPostRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - exporterUrl string
//   - body io.Reader
//   - pathParams []string
func (_e *mockExporterApiClient_Expecter) DoPostRequest(ctx interface{}, exporterUrl interface{}, body interface{}, pathParams interface{}) *mockExporterApiClient_DoPostRequest_Call {
	return &mockExporterApiClient_DoPostRequest_Call{Call: _e.mock.On("DoPostRequest", ctx, exporterUrl, body, pathParams)}
}

func (_c *mockExporterApiClient_DoPostRequest_Call) Run(run func(ctx context.Context, exporterUrl string, body io.Reader, pathParams []string)) *mockExporterApiClient_DoPostRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].([]string))
	})
	return _c
}

func (_c *mockExporterApiClient_DoPostRequest_Call) Return(result []byte, err error) *mockExporterApiClient_DoPostRequest_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockExporterApiClient_DoPostRequest_Call) RunAndReturn(run func(context.Context, string, io.Reader, []string) ([]byte, error)) *mockExporterApiClient_DoPostRequest_Call {
	_c.Call.Return(run)
	return _c
}

// newMockExporterApiClient creates a new instance of mockExporterApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockExporterApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockExporterApiClient {
	mock := &mockExporterApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
