// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockLooper is an autogenerated mock type for the looper type
type mockLooper struct {
	mock.Mock
}

type mockLooper_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLooper) EXPECT() *mockLooper_Expecter {
	return &mockLooper_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: jobClosure
func (_m *mockLooper) Run(jobClosure func(context.Context) error) {
	_m.Called(jobClosure)
}

// mockLooper_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockLooper_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - jobClosure func(context.Context) error
func (_e *mockLooper_Expecter) Run(jobClosure interface{}) *mockLooper_Run_Call {
	return &mockLooper_Run_Call{Call: _e.mock.On("Run", jobClosure)}
}

func (_c *mockLooper_Run_Call) Run(run func(jobClosure func(context.Context) error)) *mockLooper_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(context.Context) error))
	})
	return _c
}

func (_c *mockLooper_Run_Call) Return() *mockLooper_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockLooper_Run_Call) RunAndReturn(run func(func(context.Context) error)) *mockLooper_Run_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *mockLooper) Stop() {
	_m.Called()
}

// mockLooper_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockLooper_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *mockLooper_Expecter) Stop() *mockLooper_Stop_Call {
	return &mockLooper_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *mockLooper_Stop_Call) Run(run func()) *mockLooper_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockLooper_Stop_Call) Return() *mockLooper_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockLooper_Stop_Call) RunAndReturn(run func()) *mockLooper_Stop_Call {
	_c.Run(run)
	return _c
}

// newMockLooper creates a new instance of mockLooper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLooper(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLooper {
	mock := &mockLooper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
