// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// mockFile is an autogenerated mock type for the file type
type mockFile struct {
	mock.Mock
}

type mockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFile) EXPECT() *mockFile_Expecter {
	return &mockFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *mockFile) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockFile_Expecter) Close() *mockFile_Close_Call {
	return &mockFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockFile_Close_Call) Run(run func()) *mockFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockFile_Close_Call) Return(_a0 error) *mockFile_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFile_Close_Call) RunAndReturn(run func() error) *mockFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *mockFile) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type mockFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *mockFile_Expecter) Write(p interface{}) *mockFile_Write_Call {
	return &mockFile_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *mockFile_Write_Call) Run(run func(p []byte)) *mockFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *mockFile_Write_Call) Return(n int, err error) *mockFile_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockFile_Write_Call) RunAndReturn(run func([]byte) (int, error)) *mockFile_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteString provides a mock function with given fields: s
func (_m *mockFile) WriteString(s string) (int, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for WriteString")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFile_WriteString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteString'
type mockFile_WriteString_Call struct {
	*mock.Call
}

// WriteString is a helper method to define mock.On call
//   - s string
func (_e *mockFile_Expecter) WriteString(s interface{}) *mockFile_WriteString_Call {
	return &mockFile_WriteString_Call{Call: _e.mock.On("WriteString", s)}
}

func (_c *mockFile_WriteString_Call) Run(run func(s string)) *mockFile_WriteString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockFile_WriteString_Call) Return(n int, err error) *mockFile_WriteString_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockFile_WriteString_Call) RunAndReturn(run func(string) (int, error)) *mockFile_WriteString_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFile creates a new instance of mockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFile {
	mock := &mockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
