// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// mockOsReadFile is an autogenerated mock type for the osReadFile type
type mockOsReadFile struct {
	mock.Mock
}

type mockOsReadFile_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOsReadFile) EXPECT() *mockOsReadFile_Expecter {
	return &mockOsReadFile_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name
func (_m *mockOsReadFile) Execute(name string) ([]byte, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsReadFile_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockOsReadFile_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
func (_e *mockOsReadFile_Expecter) Execute(name interface{}) *mockOsReadFile_Execute_Call {
	return &mockOsReadFile_Execute_Call{Call: _e.mock.On("Execute", name)}
}

func (_c *mockOsReadFile_Execute_Call) Run(run func(name string)) *mockOsReadFile_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsReadFile_Execute_Call) Return(_a0 []byte, _a1 error) *mockOsReadFile_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsReadFile_Execute_Call) RunAndReturn(run func(string) ([]byte, error)) *mockOsReadFile_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOsReadFile creates a new instance of mockOsReadFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOsReadFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOsReadFile {
	mock := &mockOsReadFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
