// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Mocklooper is an autogenerated mock type for the looper type
type Mocklooper struct {
	mock.Mock
}

type Mocklooper_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocklooper) EXPECT() *Mocklooper_Expecter {
	return &Mocklooper_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: jobClosure
func (_m *Mocklooper) Run(jobClosure func(context.Context) error) {
	_m.Called(jobClosure)
}

// Mocklooper_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Mocklooper_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - jobClosure func(context.Context) error
func (_e *Mocklooper_Expecter) Run(jobClosure interface{}) *Mocklooper_Run_Call {
	return &Mocklooper_Run_Call{Call: _e.mock.On("Run", jobClosure)}
}

func (_c *Mocklooper_Run_Call) Run(run func(jobClosure func(context.Context) error)) *Mocklooper_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(context.Context) error))
	})
	return _c
}

func (_c *Mocklooper_Run_Call) Return() *Mocklooper_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mocklooper_Run_Call) RunAndReturn(run func(func(context.Context) error)) *Mocklooper_Run_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Mocklooper) Stop() {
	_m.Called()
}

// Mocklooper_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Mocklooper_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Mocklooper_Expecter) Stop() *Mocklooper_Stop_Call {
	return &Mocklooper_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Mocklooper_Stop_Call) Run(run func()) *Mocklooper_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mocklooper_Stop_Call) Return() *Mocklooper_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Mocklooper_Stop_Call) RunAndReturn(run func()) *Mocklooper_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMocklooper creates a new instance of Mocklooper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocklooper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocklooper {
	mock := &Mocklooper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
