// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/batch/v1"
)

// mockJobProvider is an autogenerated mock type for the jobProvider type
type mockJobProvider struct {
	mock.Mock
}

// CreateImportJob provides a mock function with given fields: ctx
func (_m *mockJobProvider) CreateImportJob(ctx context.Context) (*v1.Job, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateImportJob")
	}

	var r0 *v1.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*v1.Job, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *v1.Job); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockJobProvider creates a new instance of mockJobProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockJobProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockJobProvider {
	mock := &mockJobProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
