// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockSyncer is an autogenerated mock type for the Syncer type
type MockSyncer struct {
	mock.Mock
}

type MockSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSyncer) EXPECT() *MockSyncer_Expecter {
	return &MockSyncer_Expecter{mock: &_m.Mock}
}

// Sync provides a mock function with given fields: source, destination
func (_m *MockSyncer) Sync(source string, destination string) error {
	ret := _m.Called(source, destination)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(source, destination)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSyncer_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockSyncer_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - source string
//   - destination string
func (_e *MockSyncer_Expecter) Sync(source interface{}, destination interface{}) *MockSyncer_Sync_Call {
	return &MockSyncer_Sync_Call{Call: _e.mock.On("Sync", source, destination)}
}

func (_c *MockSyncer_Sync_Call) Run(run func(source string, destination string)) *MockSyncer_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSyncer_Sync_Call) Return(_a0 error) *MockSyncer_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSyncer_Sync_Call) RunAndReturn(run func(string, string) error) *MockSyncer_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSyncer creates a new instance of MockSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncer {
	mock := &MockSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
