// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockSystemInfoValidator is an autogenerated mock type for the systemInfoValidator type
type mockSystemInfoValidator struct {
	mock.Mock
}

type mockSystemInfoValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSystemInfoValidator) EXPECT() *mockSystemInfoValidator_Expecter {
	return &mockSystemInfoValidator_Expecter{mock: &_m.Mock}
}

// ValidateSystemInfo provides a mock function with given fields: ctx
func (_m *mockSystemInfoValidator) ValidateSystemInfo(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSystemInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSystemInfoValidator_ValidateSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSystemInfo'
type mockSystemInfoValidator_ValidateSystemInfo_Call struct {
	*mock.Call
}

// ValidateSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSystemInfoValidator_Expecter) ValidateSystemInfo(ctx interface{}) *mockSystemInfoValidator_ValidateSystemInfo_Call {
	return &mockSystemInfoValidator_ValidateSystemInfo_Call{Call: _e.mock.On("ValidateSystemInfo", ctx)}
}

func (_c *mockSystemInfoValidator_ValidateSystemInfo_Call) Run(run func(ctx context.Context)) *mockSystemInfoValidator_ValidateSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockSystemInfoValidator_ValidateSystemInfo_Call) Return(_a0 error) *mockSystemInfoValidator_ValidateSystemInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSystemInfoValidator_ValidateSystemInfo_Call) RunAndReturn(run func(context.Context) error) *mockSystemInfoValidator_ValidateSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSystemInfoValidator creates a new instance of mockSystemInfoValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSystemInfoValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSystemInfoValidator {
	mock := &mockSystemInfoValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
