// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	configuration "github.com/cloudogu/ces-importer/configuration"
	mock "github.com/stretchr/testify/mock"
)

// mockLoggingInitializer is an autogenerated mock type for the loggingInitializer type
type mockLoggingInitializer struct {
	mock.Mock
}

type mockLoggingInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockLoggingInitializer) EXPECT() *mockLoggingInitializer_Expecter {
	return &mockLoggingInitializer_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: conf
func (_m *mockLoggingInitializer) Execute(conf configuration.Configuration) error {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(configuration.Configuration) error); ok {
		r0 = rf(conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockLoggingInitializer_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockLoggingInitializer_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - conf configuration.Configuration
func (_e *mockLoggingInitializer_Expecter) Execute(conf interface{}) *mockLoggingInitializer_Execute_Call {
	return &mockLoggingInitializer_Execute_Call{Call: _e.mock.On("Execute", conf)}
}

func (_c *mockLoggingInitializer_Execute_Call) Run(run func(conf configuration.Configuration)) *mockLoggingInitializer_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(configuration.Configuration))
	})
	return _c
}

func (_c *mockLoggingInitializer_Execute_Call) Return(_a0 error) *mockLoggingInitializer_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockLoggingInitializer_Execute_Call) RunAndReturn(run func(configuration.Configuration) error) *mockLoggingInitializer_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockLoggingInitializer creates a new instance of mockLoggingInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLoggingInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLoggingInitializer {
	mock := &mockLoggingInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
