// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	configuration "github.com/cloudogu/ces-importer/configuration"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguVolumeSyncer is an autogenerated mock type for the doguVolumeSyncer type
type mockDoguVolumeSyncer struct {
	mock.Mock
}

type mockDoguVolumeSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguVolumeSyncer) EXPECT() *mockDoguVolumeSyncer_Expecter {
	return &mockDoguVolumeSyncer_Expecter{mock: &_m.Mock}
}

// SyncDogu provides a mock function with given fields: ctx, port, source, destination, pattern, verbose
func (_m *mockDoguVolumeSyncer) SyncDogu(ctx context.Context, port int, source string, destination string, pattern configuration.Exclude, verbose bool) error {
	ret := _m.Called(ctx, port, source, destination, pattern, verbose)

	if len(ret) == 0 {
		panic("no return value specified for SyncDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, configuration.Exclude, bool) error); ok {
		r0 = rf(ctx, port, source, destination, pattern, verbose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguVolumeSyncer_SyncDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncDogu'
type mockDoguVolumeSyncer_SyncDogu_Call struct {
	*mock.Call
}

// SyncDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - port int
//   - source string
//   - destination string
//   - pattern configuration.Exclude
//   - verbose bool
func (_e *mockDoguVolumeSyncer_Expecter) SyncDogu(ctx interface{}, port interface{}, source interface{}, destination interface{}, pattern interface{}, verbose interface{}) *mockDoguVolumeSyncer_SyncDogu_Call {
	return &mockDoguVolumeSyncer_SyncDogu_Call{Call: _e.mock.On("SyncDogu", ctx, port, source, destination, pattern, verbose)}
}

func (_c *mockDoguVolumeSyncer_SyncDogu_Call) Run(run func(ctx context.Context, port int, source string, destination string, pattern configuration.Exclude, verbose bool)) *mockDoguVolumeSyncer_SyncDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string), args[4].(configuration.Exclude), args[5].(bool))
	})
	return _c
}

func (_c *mockDoguVolumeSyncer_SyncDogu_Call) Return(_a0 error) *mockDoguVolumeSyncer_SyncDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguVolumeSyncer_SyncDogu_Call) RunAndReturn(run func(context.Context, int, string, string, configuration.Exclude, bool) error) *mockDoguVolumeSyncer_SyncDogu_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguVolumeSyncer creates a new instance of mockDoguVolumeSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguVolumeSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguVolumeSyncer {
	mock := &mockDoguVolumeSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
