// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// MockdoguStarter is an autogenerated mock type for the doguStarter type
type MockdoguStarter struct {
	mock.Mock
}

type MockdoguStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdoguStarter) EXPECT() *MockdoguStarter_Expecter {
	return &MockdoguStarter_Expecter{mock: &_m.Mock}
}

// StartDogu provides a mock function with given fields: ctx, dogu
func (_m *MockdoguStarter) StartDogu(ctx context.Context, dogu exporter.Dogu) error {
	ret := _m.Called(ctx, dogu)

	if len(ret) == 0 {
		panic("no return value specified for StartDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, exporter.Dogu) error); ok {
		r0 = rf(ctx, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdoguStarter_StartDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartDogu'
type MockdoguStarter_StartDogu_Call struct {
	*mock.Call
}

// StartDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu exporter.Dogu
func (_e *MockdoguStarter_Expecter) StartDogu(ctx interface{}, dogu interface{}) *MockdoguStarter_StartDogu_Call {
	return &MockdoguStarter_StartDogu_Call{Call: _e.mock.On("StartDogu", ctx, dogu)}
}

func (_c *MockdoguStarter_StartDogu_Call) Run(run func(ctx context.Context, dogu exporter.Dogu)) *MockdoguStarter_StartDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exporter.Dogu))
	})
	return _c
}

func (_c *MockdoguStarter_StartDogu_Call) Return(_a0 error) *MockdoguStarter_StartDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdoguStarter_StartDogu_Call) RunAndReturn(run func(context.Context, exporter.Dogu) error) *MockdoguStarter_StartDogu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdoguStarter creates a new instance of MockdoguStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdoguStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdoguStarter {
	mock := &MockdoguStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
