// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MocksystemInfoValidator is an autogenerated mock type for the systemInfoValidator type
type MocksystemInfoValidator struct {
	mock.Mock
}

type MocksystemInfoValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksystemInfoValidator) EXPECT() *MocksystemInfoValidator_Expecter {
	return &MocksystemInfoValidator_Expecter{mock: &_m.Mock}
}

// ValidateSystemInfo provides a mock function with no fields
func (_m *MocksystemInfoValidator) ValidateSystemInfo() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateSystemInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MocksystemInfoValidator_ValidateSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSystemInfo'
type MocksystemInfoValidator_ValidateSystemInfo_Call struct {
	*mock.Call
}

// ValidateSystemInfo is a helper method to define mock.On call
func (_e *MocksystemInfoValidator_Expecter) ValidateSystemInfo() *MocksystemInfoValidator_ValidateSystemInfo_Call {
	return &MocksystemInfoValidator_ValidateSystemInfo_Call{Call: _e.mock.On("ValidateSystemInfo")}
}

func (_c *MocksystemInfoValidator_ValidateSystemInfo_Call) Run(run func()) *MocksystemInfoValidator_ValidateSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MocksystemInfoValidator_ValidateSystemInfo_Call) Return(_a0 error) *MocksystemInfoValidator_ValidateSystemInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocksystemInfoValidator_ValidateSystemInfo_Call) RunAndReturn(run func() error) *MocksystemInfoValidator_ValidateSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksystemInfoValidator creates a new instance of MocksystemInfoValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksystemInfoValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksystemInfoValidator {
	mock := &MocksystemInfoValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
