// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// MockdoguStopper is an autogenerated mock type for the doguStopper type
type MockdoguStopper struct {
	mock.Mock
}

type MockdoguStopper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdoguStopper) EXPECT() *MockdoguStopper_Expecter {
	return &MockdoguStopper_Expecter{mock: &_m.Mock}
}

// StopDogu provides a mock function with given fields: ctx, dogu
func (_m *MockdoguStopper) StopDogu(ctx context.Context, dogu exporter.Dogu) error {
	ret := _m.Called(ctx, dogu)

	if len(ret) == 0 {
		panic("no return value specified for StopDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, exporter.Dogu) error); ok {
		r0 = rf(ctx, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdoguStopper_StopDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopDogu'
type MockdoguStopper_StopDogu_Call struct {
	*mock.Call
}

// StopDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu exporter.Dogu
func (_e *MockdoguStopper_Expecter) StopDogu(ctx interface{}, dogu interface{}) *MockdoguStopper_StopDogu_Call {
	return &MockdoguStopper_StopDogu_Call{Call: _e.mock.On("StopDogu", ctx, dogu)}
}

func (_c *MockdoguStopper_StopDogu_Call) Run(run func(ctx context.Context, dogu exporter.Dogu)) *MockdoguStopper_StopDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exporter.Dogu))
	})
	return _c
}

func (_c *MockdoguStopper_StopDogu_Call) Return(_a0 error) *MockdoguStopper_StopDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdoguStopper_StopDogu_Call) RunAndReturn(run func(context.Context, exporter.Dogu) error) *MockdoguStopper_StopDogu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdoguStopper creates a new instance of MockdoguStopper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdoguStopper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdoguStopper {
	mock := &MockdoguStopper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
