// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	configuration "github.com/cloudogu/ces-importer/configuration"
	mock "github.com/stretchr/testify/mock"
)

// MocksystemInfoProvider is an autogenerated mock type for the systemInfoProvider type
type MocksystemInfoProvider struct {
	mock.Mock
}

type MocksystemInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksystemInfoProvider) EXPECT() *MocksystemInfoProvider_Expecter {
	return &MocksystemInfoProvider_Expecter{mock: &_m.Mock}
}

// GetExporterSystemInfo provides a mock function with given fields: conf
func (_m *MocksystemInfoProvider) getExporterSystemInfo(conf configuration.Configuration) (*systemInfo, error) {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for getExporterSystemInfo")
	}

	var r0 *systemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(configuration.Configuration) (*systemInfo, error)); ok {
		return rf(conf)
	}
	if rf, ok := ret.Get(0).(func(configuration.Configuration) *systemInfo); ok {
		r0 = rf(conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*systemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(configuration.Configuration) error); ok {
		r1 = rf(conf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MocksystemInfoProvider_GetExporterSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getExporterSystemInfo'
type MocksystemInfoProvider_GetExporterSystemInfo_Call struct {
	*mock.Call
}

// GetExporterSystemInfo is a helper method to define mock.On call
//   - conf configuration.Configuration
func (_e *MocksystemInfoProvider_Expecter) GetExporterSystemInfo(conf interface{}) *MocksystemInfoProvider_GetExporterSystemInfo_Call {
	return &MocksystemInfoProvider_GetExporterSystemInfo_Call{Call: _e.mock.On("getExporterSystemInfo", conf)}
}

func (_c *MocksystemInfoProvider_GetExporterSystemInfo_Call) Run(run func(conf configuration.Configuration)) *MocksystemInfoProvider_GetExporterSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(configuration.Configuration))
	})
	return _c
}

func (_c *MocksystemInfoProvider_GetExporterSystemInfo_Call) Return(_a0 *systemInfo, _a1 error) *MocksystemInfoProvider_GetExporterSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MocksystemInfoProvider_GetExporterSystemInfo_Call) RunAndReturn(run func(configuration.Configuration) (*systemInfo, error)) *MocksystemInfoProvider_GetExporterSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemInfo provides a mock function with no fields
func (_m *MocksystemInfoProvider) getSystemInfo() (*systemInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSystemInfo")
	}

	var r0 *systemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (*systemInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *systemInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*systemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MocksystemInfoProvider_GetSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSystemInfo'
type MocksystemInfoProvider_GetSystemInfo_Call struct {
	*mock.Call
}

// GetSystemInfo is a helper method to define mock.On call
func (_e *MocksystemInfoProvider_Expecter) GetSystemInfo() *MocksystemInfoProvider_GetSystemInfo_Call {
	return &MocksystemInfoProvider_GetSystemInfo_Call{Call: _e.mock.On("getSystemInfo")}
}

func (_c *MocksystemInfoProvider_GetSystemInfo_Call) Run(run func()) *MocksystemInfoProvider_GetSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MocksystemInfoProvider_GetSystemInfo_Call) Return(_a0 *systemInfo, _a1 error) *MocksystemInfoProvider_GetSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MocksystemInfoProvider_GetSystemInfo_Call) RunAndReturn(run func() (*systemInfo, error)) *MocksystemInfoProvider_GetSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// getPvcClient provides a mock function with no fields
func (_m *MocksystemInfoProvider) getPvcClient() kubernetesClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getPvcClient")
	}

	var r0 kubernetesClient
	if rf, ok := ret.Get(0).(func() kubernetesClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetesClient)
		}
	}

	return r0
}

// MocksystemInfoProvider_getPvcClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPvcClient'
type MocksystemInfoProvider_getPvcClient_Call struct {
	*mock.Call
}

// getPvcClient is a helper method to define mock.On call
func (_e *MocksystemInfoProvider_Expecter) getPvcClient() *MocksystemInfoProvider_getPvcClient_Call {
	return &MocksystemInfoProvider_getPvcClient_Call{Call: _e.mock.On("getPvcClient")}
}

func (_c *MocksystemInfoProvider_getPvcClient_Call) Run(run func()) *MocksystemInfoProvider_getPvcClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MocksystemInfoProvider_getPvcClient_Call) Return(_a0 kubernetesClient) *MocksystemInfoProvider_getPvcClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocksystemInfoProvider_getPvcClient_Call) RunAndReturn(run func() kubernetesClient) *MocksystemInfoProvider_getPvcClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksystemInfoProvider creates a new instance of MocksystemInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksystemInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksystemInfoProvider {
	mock := &MocksystemInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
