// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockPvcClient is an autogenerated mock type for the pvcClient type
type mockPvcClient struct {
	mock.Mock
}

type mockPvcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPvcClient) EXPECT() *mockPvcClient_Expecter {
	return &mockPvcClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockPvcClient) Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockPvcClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *mockPvcClient_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockPvcClient_Get_Call {
	return &mockPvcClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockPvcClient_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *mockPvcClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *mockPvcClient_Get_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *mockPvcClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcClient_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *mockPvcClient) Update(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts v1.UpdateOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, v1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, v1.UpdateOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.PersistentVolumeClaim, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockPvcClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockPvcClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *corev1.PersistentVolumeClaim
//   - opts v1.UpdateOptions
func (_e *mockPvcClient_Expecter) Update(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *mockPvcClient_Update_Call {
	return &mockPvcClient_Update_Call{Call: _e.mock.On("Update", ctx, persistentVolumeClaim, opts)}
}

func (_c *mockPvcClient_Update_Call) Run(run func(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts v1.UpdateOptions)) *mockPvcClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.PersistentVolumeClaim), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *mockPvcClient_Update_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *mockPvcClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockPvcClient_Update_Call) RunAndReturn(run func(context.Context, *corev1.PersistentVolumeClaim, v1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)) *mockPvcClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPvcClient creates a new instance of mockPvcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPvcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPvcClient {
	mock := &mockPvcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
