// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	configuration "github.com/cloudogu/ces-importer/configuration"
	mock "github.com/stretchr/testify/mock"
)

// mockSystemInfoProvider is an autogenerated mock type for the systemInfoProvider type
type mockSystemInfoProvider struct {
	mock.Mock
}

type mockSystemInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSystemInfoProvider) EXPECT() *mockSystemInfoProvider_Expecter {
	return &mockSystemInfoProvider_Expecter{mock: &_m.Mock}
}

// getExporterSystemInfo provides a mock function with given fields: conf
func (_m *mockSystemInfoProvider) getExporterSystemInfo(conf configuration.Configuration) (*systemInfo, error) {
	ret := _m.Called(conf)

	if len(ret) == 0 {
		panic("no return value specified for getExporterSystemInfo")
	}

	var r0 *systemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(configuration.Configuration) (*systemInfo, error)); ok {
		return rf(conf)
	}
	if rf, ok := ret.Get(0).(func(configuration.Configuration) *systemInfo); ok {
		r0 = rf(conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*systemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(configuration.Configuration) error); ok {
		r1 = rf(conf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSystemInfoProvider_getExporterSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getExporterSystemInfo'
type mockSystemInfoProvider_getExporterSystemInfo_Call struct {
	*mock.Call
}

// getExporterSystemInfo is a helper method to define mock.On call
//   - conf configuration.Configuration
func (_e *mockSystemInfoProvider_Expecter) getExporterSystemInfo(conf interface{}) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	return &mockSystemInfoProvider_getExporterSystemInfo_Call{Call: _e.mock.On("getExporterSystemInfo", conf)}
}

func (_c *mockSystemInfoProvider_getExporterSystemInfo_Call) Run(run func(conf configuration.Configuration)) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(configuration.Configuration))
	})
	return _c
}

func (_c *mockSystemInfoProvider_getExporterSystemInfo_Call) Return(_a0 *systemInfo, _a1 error) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSystemInfoProvider_getExporterSystemInfo_Call) RunAndReturn(run func(configuration.Configuration) (*systemInfo, error)) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// getPvcClient provides a mock function with no fields
func (_m *mockSystemInfoProvider) getPvcClient() kubernetesClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getPvcClient")
	}

	var r0 kubernetesClient
	if rf, ok := ret.Get(0).(func() kubernetesClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetesClient)
		}
	}

	return r0
}

// mockSystemInfoProvider_getPvcClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPvcClient'
type mockSystemInfoProvider_getPvcClient_Call struct {
	*mock.Call
}

// getPvcClient is a helper method to define mock.On call
func (_e *mockSystemInfoProvider_Expecter) getPvcClient() *mockSystemInfoProvider_getPvcClient_Call {
	return &mockSystemInfoProvider_getPvcClient_Call{Call: _e.mock.On("getPvcClient")}
}

func (_c *mockSystemInfoProvider_getPvcClient_Call) Run(run func()) *mockSystemInfoProvider_getPvcClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockSystemInfoProvider_getPvcClient_Call) Return(_a0 kubernetesClient) *mockSystemInfoProvider_getPvcClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSystemInfoProvider_getPvcClient_Call) RunAndReturn(run func() kubernetesClient) *mockSystemInfoProvider_getPvcClient_Call {
	_c.Call.Return(run)
	return _c
}

// getSystemInfo provides a mock function with no fields
func (_m *mockSystemInfoProvider) getSystemInfo() (*systemInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSystemInfo")
	}

	var r0 *systemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (*systemInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *systemInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*systemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSystemInfoProvider_getSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSystemInfo'
type mockSystemInfoProvider_getSystemInfo_Call struct {
	*mock.Call
}

// getSystemInfo is a helper method to define mock.On call
func (_e *mockSystemInfoProvider_Expecter) getSystemInfo() *mockSystemInfoProvider_getSystemInfo_Call {
	return &mockSystemInfoProvider_getSystemInfo_Call{Call: _e.mock.On("getSystemInfo")}
}

func (_c *mockSystemInfoProvider_getSystemInfo_Call) Run(run func()) *mockSystemInfoProvider_getSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockSystemInfoProvider_getSystemInfo_Call) Return(_a0 *systemInfo, _a1 error) *mockSystemInfoProvider_getSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSystemInfoProvider_getSystemInfo_Call) RunAndReturn(run func() (*systemInfo, error)) *mockSystemInfoProvider_getSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSystemInfoProvider creates a new instance of mockSystemInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSystemInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSystemInfoProvider {
	mock := &mockSystemInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
