// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	ecosystem "github.com/cloudogu/k8s-component-operator/pkg/api/ecosystem"
	mock "github.com/stretchr/testify/mock"
)

// MockecosystemComponentClient is an autogenerated mock type for the ecosystemComponentClient type
type MockecosystemComponentClient struct {
	mock.Mock
}

type MockecosystemComponentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockecosystemComponentClient) EXPECT() *MockecosystemComponentClient_Expecter {
	return &MockecosystemComponentClient_Expecter{mock: &_m.Mock}
}

// Components provides a mock function with given fields: namespace
func (_m *MockecosystemComponentClient) Components(namespace string) ecosystem.ComponentInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Components")
	}

	var r0 ecosystem.ComponentInterface
	if rf, ok := ret.Get(0).(func(string) ecosystem.ComponentInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ecosystem.ComponentInterface)
		}
	}

	return r0
}

// MockecosystemComponentClient_Components_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Components'
type MockecosystemComponentClient_Components_Call struct {
	*mock.Call
}

// Components is a helper method to define mock.On call
//   - namespace string
func (_e *MockecosystemComponentClient_Expecter) Components(namespace interface{}) *MockecosystemComponentClient_Components_Call {
	return &MockecosystemComponentClient_Components_Call{Call: _e.mock.On("Components", namespace)}
}

func (_c *MockecosystemComponentClient_Components_Call) Run(run func(namespace string)) *MockecosystemComponentClient_Components_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockecosystemComponentClient_Components_Call) Return(_a0 ecosystem.ComponentInterface) *MockecosystemComponentClient_Components_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockecosystemComponentClient_Components_Call) RunAndReturn(run func(string) ecosystem.ComponentInterface) *MockecosystemComponentClient_Components_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockecosystemComponentClient creates a new instance of MockecosystemComponentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockecosystemComponentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockecosystemComponentClient {
	mock := &MockecosystemComponentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
