// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	context "context"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"
	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguDescriptorRepo is an autogenerated mock type for the doguDescriptorRepo type
type mockDoguDescriptorRepo struct {
	mock.Mock
}

type mockDoguDescriptorRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguDescriptorRepo) EXPECT() *mockDoguDescriptorRepo_Expecter {
	return &mockDoguDescriptorRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, doguVersion
func (_m *mockDoguDescriptorRepo) Get(ctx context.Context, doguVersion dogu.SimpleNameVersion) (*core.Dogu, error) {
	ret := _m.Called(ctx, doguVersion)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleNameVersion) (*core.Dogu, error)); ok {
		return rf(ctx, doguVersion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleNameVersion) *core.Dogu); ok {
		r0 = rf(ctx, doguVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dogu.SimpleNameVersion) error); ok {
		r1 = rf(ctx, doguVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguDescriptorRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockDoguDescriptorRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - doguVersion dogu.SimpleNameVersion
func (_e *mockDoguDescriptorRepo_Expecter) Get(ctx interface{}, doguVersion interface{}) *mockDoguDescriptorRepo_Get_Call {
	return &mockDoguDescriptorRepo_Get_Call{Call: _e.mock.On("Get", ctx, doguVersion)}
}

func (_c *mockDoguDescriptorRepo_Get_Call) Run(run func(ctx context.Context, doguVersion dogu.SimpleNameVersion)) *mockDoguDescriptorRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dogu.SimpleNameVersion))
	})
	return _c
}

func (_c *mockDoguDescriptorRepo_Get_Call) Return(_a0 *core.Dogu, _a1 error) *mockDoguDescriptorRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguDescriptorRepo_Get_Call) RunAndReturn(run func(context.Context, dogu.SimpleNameVersion) (*core.Dogu, error)) *mockDoguDescriptorRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguDescriptorRepo creates a new instance of mockDoguDescriptorRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguDescriptorRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguDescriptorRepo {
	mock := &mockDoguDescriptorRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
