// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	context "context"

	apiv1 "github.com/cloudogu/k8s-component-operator/pkg/api/v1"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockComponentLister is an autogenerated mock type for the componentLister type
type MockComponentLister struct {
	mock.Mock
}

type MockComponentLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComponentLister) EXPECT() *MockComponentLister_Expecter {
	return &MockComponentLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockComponentLister) List(ctx context.Context, opts v1.ListOptions) (*apiv1.ComponentList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apiv1.ComponentList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*apiv1.ComponentList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *apiv1.ComponentList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ComponentList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockComponentLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockComponentLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *MockComponentLister_Expecter) List(ctx interface{}, opts interface{}) *MockComponentLister_List_Call {
	return &MockComponentLister_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockComponentLister_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *MockComponentLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *MockComponentLister_List_Call) Return(_a0 *apiv1.ComponentList, _a1 error) *MockComponentLister_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockComponentLister_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*apiv1.ComponentList, error)) *MockComponentLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockComponentLister creates a new instance of MockComponentLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComponentLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComponentLister {
	mock := &MockComponentLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
