// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// mockSystemInfoApiClient is an autogenerated mock type for the systemInfoApiClient type
type mockSystemInfoApiClient struct {
	mock.Mock
}

type mockSystemInfoApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSystemInfoApiClient) EXPECT() *mockSystemInfoApiClient_Expecter {
	return &mockSystemInfoApiClient_Expecter{mock: &_m.Mock}
}

// GetSystemInfo provides a mock function with given fields: ctx
func (_m *mockSystemInfoApiClient) GetSystemInfo(ctx context.Context) (*exporter.SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemInfo")
	}

	var r0 *exporter.SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*exporter.SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *exporter.SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exporter.SystemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSystemInfoApiClient_GetSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemInfo'
type mockSystemInfoApiClient_GetSystemInfo_Call struct {
	*mock.Call
}

// GetSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSystemInfoApiClient_Expecter) GetSystemInfo(ctx interface{}) *mockSystemInfoApiClient_GetSystemInfo_Call {
	return &mockSystemInfoApiClient_GetSystemInfo_Call{Call: _e.mock.On("GetSystemInfo", ctx)}
}

func (_c *mockSystemInfoApiClient_GetSystemInfo_Call) Run(run func(ctx context.Context)) *mockSystemInfoApiClient_GetSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockSystemInfoApiClient_GetSystemInfo_Call) Return(_a0 *exporter.SystemInfo, _a1 error) *mockSystemInfoApiClient_GetSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSystemInfoApiClient_GetSystemInfo_Call) RunAndReturn(run func(context.Context) (*exporter.SystemInfo, error)) *mockSystemInfoApiClient_GetSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSystemInfoApiClient creates a new instance of mockSystemInfoApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSystemInfoApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSystemInfoApiClient {
	mock := &mockSystemInfoApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
