// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	ecoSystem "github.com/cloudogu/k8s-dogu-operator/v3/api/ecoSystem"
	mock "github.com/stretchr/testify/mock"
)

// MockecosystemDogusClient is an autogenerated mock type for the ecosystemDogusClient type
type MockecosystemDogusClient struct {
	mock.Mock
}

type MockecosystemDogusClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockecosystemDogusClient) EXPECT() *MockecosystemDogusClient_Expecter {
	return &MockecosystemDogusClient_Expecter{mock: &_m.Mock}
}

// DoguRestarts provides a mock function with given fields: namespace
func (_m *MockecosystemDogusClient) DoguRestarts(namespace string) ecoSystem.DoguRestartInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for DoguRestarts")
	}

	var r0 ecoSystem.DoguRestartInterface
	if rf, ok := ret.Get(0).(func(string) ecoSystem.DoguRestartInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ecoSystem.DoguRestartInterface)
		}
	}

	return r0
}

// MockecosystemDogusClient_DoguRestarts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoguRestarts'
type MockecosystemDogusClient_DoguRestarts_Call struct {
	*mock.Call
}

// DoguRestarts is a helper method to define mock.On call
//   - namespace string
func (_e *MockecosystemDogusClient_Expecter) DoguRestarts(namespace interface{}) *MockecosystemDogusClient_DoguRestarts_Call {
	return &MockecosystemDogusClient_DoguRestarts_Call{Call: _e.mock.On("DoguRestarts", namespace)}
}

func (_c *MockecosystemDogusClient_DoguRestarts_Call) Run(run func(namespace string)) *MockecosystemDogusClient_DoguRestarts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockecosystemDogusClient_DoguRestarts_Call) Return(_a0 ecoSystem.DoguRestartInterface) *MockecosystemDogusClient_DoguRestarts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockecosystemDogusClient_DoguRestarts_Call) RunAndReturn(run func(string) ecoSystem.DoguRestartInterface) *MockecosystemDogusClient_DoguRestarts_Call {
	_c.Call.Return(run)
	return _c
}

// Dogus provides a mock function with given fields: namespace
func (_m *MockecosystemDogusClient) Dogus(namespace string) ecoSystem.DoguInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Dogus")
	}

	var r0 ecoSystem.DoguInterface
	if rf, ok := ret.Get(0).(func(string) ecoSystem.DoguInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ecoSystem.DoguInterface)
		}
	}

	return r0
}

// MockecosystemDogusClient_Dogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dogus'
type MockecosystemDogusClient_Dogus_Call struct {
	*mock.Call
}

// Dogus is a helper method to define mock.On call
//   - namespace string
func (_e *MockecosystemDogusClient_Expecter) Dogus(namespace interface{}) *MockecosystemDogusClient_Dogus_Call {
	return &MockecosystemDogusClient_Dogus_Call{Call: _e.mock.On("Dogus", namespace)}
}

func (_c *MockecosystemDogusClient_Dogus_Call) Run(run func(namespace string)) *MockecosystemDogusClient_Dogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockecosystemDogusClient_Dogus_Call) Return(_a0 ecoSystem.DoguInterface) *MockecosystemDogusClient_Dogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockecosystemDogusClient_Dogus_Call) RunAndReturn(run func(string) ecoSystem.DoguInterface) *MockecosystemDogusClient_Dogus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockecosystemDogusClient creates a new instance of MockecosystemDogusClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockecosystemDogusClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockecosystemDogusClient {
	mock := &MockecosystemDogusClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
