// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// mockSystemInfoProvider is an autogenerated mock type for the systemInfoProvider type
type mockSystemInfoProvider struct {
	mock.Mock
}

type mockSystemInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSystemInfoProvider) EXPECT() *mockSystemInfoProvider_Expecter {
	return &mockSystemInfoProvider_Expecter{mock: &_m.Mock}
}

// getExporterSystemInfo provides a mock function with given fields: ctx
func (_m *mockSystemInfoProvider) getExporterSystemInfo(ctx context.Context) (*exporter.SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getExporterSystemInfo")
	}

	var r0 *exporter.SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*exporter.SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *exporter.SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exporter.SystemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSystemInfoProvider_getExporterSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getExporterSystemInfo'
type mockSystemInfoProvider_getExporterSystemInfo_Call struct {
	*mock.Call
}

// getExporterSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSystemInfoProvider_Expecter) getExporterSystemInfo(ctx interface{}) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	return &mockSystemInfoProvider_getExporterSystemInfo_Call{Call: _e.mock.On("getExporterSystemInfo", ctx)}
}

func (_c *mockSystemInfoProvider_getExporterSystemInfo_Call) Run(run func(ctx context.Context)) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockSystemInfoProvider_getExporterSystemInfo_Call) Return(_a0 *exporter.SystemInfo, _a1 error) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSystemInfoProvider_getExporterSystemInfo_Call) RunAndReturn(run func(context.Context) (*exporter.SystemInfo, error)) *mockSystemInfoProvider_getExporterSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// getImporterSystemInfo provides a mock function with given fields: ctx
func (_m *mockSystemInfoProvider) getImporterSystemInfo(ctx context.Context) (*exporter.SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for getImporterSystemInfo")
	}

	var r0 *exporter.SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*exporter.SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *exporter.SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exporter.SystemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSystemInfoProvider_getImporterSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getImporterSystemInfo'
type mockSystemInfoProvider_getImporterSystemInfo_Call struct {
	*mock.Call
}

// getImporterSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSystemInfoProvider_Expecter) getImporterSystemInfo(ctx interface{}) *mockSystemInfoProvider_getImporterSystemInfo_Call {
	return &mockSystemInfoProvider_getImporterSystemInfo_Call{Call: _e.mock.On("getImporterSystemInfo", ctx)}
}

func (_c *mockSystemInfoProvider_getImporterSystemInfo_Call) Run(run func(ctx context.Context)) *mockSystemInfoProvider_getImporterSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockSystemInfoProvider_getImporterSystemInfo_Call) Return(_a0 *exporter.SystemInfo, _a1 error) *mockSystemInfoProvider_getImporterSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSystemInfoProvider_getImporterSystemInfo_Call) RunAndReturn(run func(context.Context) (*exporter.SystemInfo, error)) *mockSystemInfoProvider_getImporterSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSystemInfoProvider creates a new instance of mockSystemInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSystemInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSystemInfoProvider {
	mock := &mockSystemInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
