// Code generated by mockery v2.53.3. DO NOT EDIT.

package systeminfo

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguVolumeResizer is an autogenerated mock type for the doguVolumeResizer type
type mockDoguVolumeResizer struct {
	mock.Mock
}

type mockDoguVolumeResizer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguVolumeResizer) EXPECT() *mockDoguVolumeResizer_Expecter {
	return &mockDoguVolumeResizer_Expecter{mock: &_m.Mock}
}

// ResizeDogusIfNeeded provides a mock function with given fields: ctx, exporterDogus, importerDogus
func (_m *mockDoguVolumeResizer) ResizeDogusIfNeeded(ctx context.Context, exporterDogus []exporter.Dogu, importerDogus []exporter.Dogu) error {
	ret := _m.Called(ctx, exporterDogus, importerDogus)

	if len(ret) == 0 {
		panic("no return value specified for ResizeDogusIfNeeded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []exporter.Dogu, []exporter.Dogu) error); ok {
		r0 = rf(ctx, exporterDogus, importerDogus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguVolumeResizer_ResizeDogusIfNeeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeDogusIfNeeded'
type mockDoguVolumeResizer_ResizeDogusIfNeeded_Call struct {
	*mock.Call
}

// ResizeDogusIfNeeded is a helper method to define mock.On call
//   - ctx context.Context
//   - exporterDogus []exporter.Dogu
//   - importerDogus []exporter.Dogu
func (_e *mockDoguVolumeResizer_Expecter) ResizeDogusIfNeeded(ctx interface{}, exporterDogus interface{}, importerDogus interface{}) *mockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	return &mockDoguVolumeResizer_ResizeDogusIfNeeded_Call{Call: _e.mock.On("ResizeDogusIfNeeded", ctx, exporterDogus, importerDogus)}
}

func (_c *mockDoguVolumeResizer_ResizeDogusIfNeeded_Call) Run(run func(ctx context.Context, exporterDogus []exporter.Dogu, importerDogus []exporter.Dogu)) *mockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]exporter.Dogu), args[2].([]exporter.Dogu))
	})
	return _c
}

func (_c *mockDoguVolumeResizer_ResizeDogusIfNeeded_Call) Return(_a0 error) *mockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguVolumeResizer_ResizeDogusIfNeeded_Call) RunAndReturn(run func(context.Context, []exporter.Dogu, []exporter.Dogu) error) *mockDoguVolumeResizer_ResizeDogusIfNeeded_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguVolumeResizer creates a new instance of mockDoguVolumeResizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguVolumeResizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguVolumeResizer {
	mock := &mockDoguVolumeResizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
