// Code generated by mockery v2.53.3. DO NOT EDIT.

package logging

import mock "github.com/stretchr/testify/mock"

// mockOsCreate is an autogenerated mock type for the osCreate type
type mockOsCreate struct {
	mock.Mock
}

type mockOsCreate_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOsCreate) EXPECT() *mockOsCreate_Expecter {
	return &mockOsCreate_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name
func (_m *mockOsCreate) Execute(name string) (File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsCreate_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockOsCreate_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
func (_e *mockOsCreate_Expecter) Execute(name interface{}) *mockOsCreate_Execute_Call {
	return &mockOsCreate_Execute_Call{Call: _e.mock.On("Execute", name)}
}

func (_c *mockOsCreate_Execute_Call) Run(run func(name string)) *mockOsCreate_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsCreate_Execute_Call) Return(_a0 File, _a1 error) *mockOsCreate_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsCreate_Execute_Call) RunAndReturn(run func(string) (File, error)) *mockOsCreate_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOsCreate creates a new instance of mockOsCreate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOsCreate(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOsCreate {
	mock := &mockOsCreate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
