// Code generated by mockery v2.53.3. DO NOT EDIT.

package logging

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// mockOsOpenFile is an autogenerated mock type for the osOpenFile type
type mockOsOpenFile struct {
	mock.Mock
}

type mockOsOpenFile_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOsOpenFile) EXPECT() *mockOsOpenFile_Expecter {
	return &mockOsOpenFile_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name, flag, perm
func (_m *mockOsOpenFile) Execute(name string, flag int, perm fs.FileMode) (File, error) {
	ret := _m.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 File
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, fs.FileMode) (File, error)); ok {
		return rf(name, flag, perm)
	}
	if rf, ok := ret.Get(0).(func(string, int, fs.FileMode) File); ok {
		r0 = rf(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(File)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, fs.FileMode) error); ok {
		r1 = rf(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsOpenFile_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockOsOpenFile_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm fs.FileMode
func (_e *mockOsOpenFile_Expecter) Execute(name interface{}, flag interface{}, perm interface{}) *mockOsOpenFile_Execute_Call {
	return &mockOsOpenFile_Execute_Call{Call: _e.mock.On("Execute", name, flag, perm)}
}

func (_c *mockOsOpenFile_Execute_Call) Run(run func(name string, flag int, perm fs.FileMode)) *mockOsOpenFile_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(fs.FileMode))
	})
	return _c
}

func (_c *mockOsOpenFile_Execute_Call) Return(_a0 File, _a1 error) *mockOsOpenFile_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsOpenFile_Execute_Call) RunAndReturn(run func(string, int, fs.FileMode) (File, error)) *mockOsOpenFile_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOsOpenFile creates a new instance of mockOsOpenFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOsOpenFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOsOpenFile {
	mock := &mockOsOpenFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
