// Code generated by mockery v2.53.3. DO NOT EDIT.

package logging

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockIoCopy is an autogenerated mock type for the ioCopy type
type mockIoCopy struct {
	mock.Mock
}

type mockIoCopy_Expecter struct {
	mock *mock.Mock
}

func (_m *mockIoCopy) EXPECT() *mockIoCopy_Expecter {
	return &mockIoCopy_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: dst, src
func (_m *mockIoCopy) Execute(dst io.Writer, src io.Reader) (int64, error) {
	ret := _m.Called(dst, src)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(io.Writer, io.Reader) (int64, error)); ok {
		return rf(dst, src)
	}
	if rf, ok := ret.Get(0).(func(io.Writer, io.Reader) int64); ok {
		r0 = rf(dst, src)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(io.Writer, io.Reader) error); ok {
		r1 = rf(dst, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockIoCopy_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockIoCopy_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - dst io.Writer
//   - src io.Reader
func (_e *mockIoCopy_Expecter) Execute(dst interface{}, src interface{}) *mockIoCopy_Execute_Call {
	return &mockIoCopy_Execute_Call{Call: _e.mock.On("Execute", dst, src)}
}

func (_c *mockIoCopy_Execute_Call) Run(run func(dst io.Writer, src io.Reader)) *mockIoCopy_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(io.Reader))
	})
	return _c
}

func (_c *mockIoCopy_Execute_Call) Return(written int64, err error) *mockIoCopy_Execute_Call {
	_c.Call.Return(written, err)
	return _c
}

func (_c *mockIoCopy_Execute_Call) RunAndReturn(run func(io.Writer, io.Reader) (int64, error)) *mockIoCopy_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockIoCopy creates a new instance of mockIoCopy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIoCopy(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIoCopy {
	mock := &mockIoCopy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
