// Code generated by mockery v2.53.3. DO NOT EDIT.

package logging

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockCreateMultiWriter is an autogenerated mock type for the createMultiWriter type
type mockCreateMultiWriter struct {
	mock.Mock
}

type mockCreateMultiWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCreateMultiWriter) EXPECT() *mockCreateMultiWriter_Expecter {
	return &mockCreateMultiWriter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: writers
func (_m *mockCreateMultiWriter) Execute(writers ...io.Writer) io.Writer {
	_va := make([]interface{}, len(writers))
	for _i := range writers {
		_va[_i] = writers[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func(...io.Writer) io.Writer); ok {
		r0 = rf(writers...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	return r0
}

// mockCreateMultiWriter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockCreateMultiWriter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - writers ...io.Writer
func (_e *mockCreateMultiWriter_Expecter) Execute(writers ...interface{}) *mockCreateMultiWriter_Execute_Call {
	return &mockCreateMultiWriter_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{}, writers...)...)}
}

func (_c *mockCreateMultiWriter_Execute_Call) Run(run func(writers ...io.Writer)) *mockCreateMultiWriter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]io.Writer, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(io.Writer)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *mockCreateMultiWriter_Execute_Call) Return(_a0 io.Writer) *mockCreateMultiWriter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCreateMultiWriter_Execute_Call) RunAndReturn(run func(...io.Writer) io.Writer) *mockCreateMultiWriter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCreateMultiWriter creates a new instance of mockCreateMultiWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCreateMultiWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCreateMultiWriter {
	mock := &mockCreateMultiWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
