// Code generated by mockery v2.53.3. DO NOT EDIT.

package logging

import mock "github.com/stretchr/testify/mock"

// mockOsRemove is an autogenerated mock type for the osRemove type
type mockOsRemove struct {
	mock.Mock
}

type mockOsRemove_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOsRemove) EXPECT() *mockOsRemove_Expecter {
	return &mockOsRemove_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name
func (_m *mockOsRemove) Execute(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOsRemove_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockOsRemove_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
func (_e *mockOsRemove_Expecter) Execute(name interface{}) *mockOsRemove_Execute_Call {
	return &mockOsRemove_Execute_Call{Call: _e.mock.On("Execute", name)}
}

func (_c *mockOsRemove_Execute_Call) Run(run func(name string)) *mockOsRemove_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsRemove_Execute_Call) Return(_a0 error) *mockOsRemove_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOsRemove_Execute_Call) RunAndReturn(run func(string) error) *mockOsRemove_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOsRemove creates a new instance of mockOsRemove. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOsRemove(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOsRemove {
	mock := &mockOsRemove{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
