// Code generated by mockery v2.53.3. DO NOT EDIT.

package manual

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
)

// mockConfigmapClient is an autogenerated mock type for the configmapClient type
type mockConfigmapClient struct {
	mock.Mock
}

type mockConfigmapClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigmapClient) EXPECT() *mockConfigmapClient_Expecter {
	return &mockConfigmapClient_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockConfigmapClient) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockConfigmapClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockConfigmapClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.DeleteOptions
func (_e *mockConfigmapClient_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockConfigmapClient_Delete_Call {
	return &mockConfigmapClient_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockConfigmapClient_Delete_Call) Run(run func(ctx context.Context, name string, opts v1.DeleteOptions)) *mockConfigmapClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.DeleteOptions))
	})
	return _c
}

func (_c *mockConfigmapClient_Delete_Call) Return(_a0 error) *mockConfigmapClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConfigmapClient_Delete_Call) RunAndReturn(run func(context.Context, string, v1.DeleteOptions) error) *mockConfigmapClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockConfigmapClient) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigmapClient_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockConfigmapClient_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockConfigmapClient_Expecter) Watch(ctx interface{}, opts interface{}) *mockConfigmapClient_Watch_Call {
	return &mockConfigmapClient_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockConfigmapClient_Watch_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockConfigmapClient_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockConfigmapClient_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockConfigmapClient_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigmapClient_Watch_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (watch.Interface, error)) *mockConfigmapClient_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigmapClient creates a new instance of mockConfigmapClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigmapClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigmapClient {
	mock := &mockConfigmapClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
