// Code generated by mockery v2.53.3. DO NOT EDIT.

package configuration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockGlobalConfigImporter is an autogenerated mock type for the globalConfigImporter type
type mockGlobalConfigImporter struct {
	mock.Mock
}

type mockGlobalConfigImporter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGlobalConfigImporter) EXPECT() *mockGlobalConfigImporter_Expecter {
	return &mockGlobalConfigImporter_Expecter{mock: &_m.Mock}
}

// importGlobalConfig provides a mock function with given fields: ctx, config
func (_m *mockGlobalConfigImporter) importGlobalConfig(ctx context.Context, config globalConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for importGlobalConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, globalConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockGlobalConfigImporter_importGlobalConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'importGlobalConfig'
type mockGlobalConfigImporter_importGlobalConfig_Call struct {
	*mock.Call
}

// importGlobalConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config globalConfig
func (_e *mockGlobalConfigImporter_Expecter) importGlobalConfig(ctx interface{}, config interface{}) *mockGlobalConfigImporter_importGlobalConfig_Call {
	return &mockGlobalConfigImporter_importGlobalConfig_Call{Call: _e.mock.On("importGlobalConfig", ctx, config)}
}

func (_c *mockGlobalConfigImporter_importGlobalConfig_Call) Run(run func(ctx context.Context, config globalConfig)) *mockGlobalConfigImporter_importGlobalConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(globalConfig))
	})
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalConfig_Call) Return(_a0 error) *mockGlobalConfigImporter_importGlobalConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalConfig_Call) RunAndReturn(run func(context.Context, globalConfig) error) *mockGlobalConfigImporter_importGlobalConfig_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGlobalConfigImporter creates a new instance of mockGlobalConfigImporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGlobalConfigImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGlobalConfigImporter {
	mock := &mockGlobalConfigImporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
