// Code generated by mockery v2.53.3. DO NOT EDIT.

package configuration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguConfigImporter is an autogenerated mock type for the doguConfigImporter type
type mockDoguConfigImporter struct {
	mock.Mock
}

type mockDoguConfigImporter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguConfigImporter) EXPECT() *mockDoguConfigImporter_Expecter {
	return &mockDoguConfigImporter_Expecter{mock: &_m.Mock}
}

// importDoguConfigs provides a mock function with given fields: ctx, config
func (_m *mockDoguConfigImporter) importDoguConfigs(ctx context.Context, config []doguConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for importDoguConfigs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []doguConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguConfigImporter_importDoguConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'importDoguConfigs'
type mockDoguConfigImporter_importDoguConfigs_Call struct {
	*mock.Call
}

// importDoguConfigs is a helper method to define mock.On call
//   - ctx context.Context
//   - config []doguConfig
func (_e *mockDoguConfigImporter_Expecter) importDoguConfigs(ctx interface{}, config interface{}) *mockDoguConfigImporter_importDoguConfigs_Call {
	return &mockDoguConfigImporter_importDoguConfigs_Call{Call: _e.mock.On("importDoguConfigs", ctx, config)}
}

func (_c *mockDoguConfigImporter_importDoguConfigs_Call) Run(run func(ctx context.Context, config []doguConfig)) *mockDoguConfigImporter_importDoguConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]doguConfig))
	})
	return _c
}

func (_c *mockDoguConfigImporter_importDoguConfigs_Call) Return(_a0 error) *mockDoguConfigImporter_importDoguConfigs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguConfigImporter_importDoguConfigs_Call) RunAndReturn(run func(context.Context, []doguConfig) error) *mockDoguConfigImporter_importDoguConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguConfigImporter creates a new instance of mockDoguConfigImporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguConfigImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguConfigImporter {
	mock := &mockDoguConfigImporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
