// Code generated by mockery v2.53.3. DO NOT EDIT.

package configuration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockBackupScheduleClient is an autogenerated mock type for the backupScheduleClient type
type mockBackupScheduleClient struct {
	mock.Mock
}

type mockBackupScheduleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBackupScheduleClient) EXPECT() *mockBackupScheduleClient_Expecter {
	return &mockBackupScheduleClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, backupSchedule, opts
func (_m *mockBackupScheduleClient) Create(ctx context.Context, backupSchedule *v1.BackupSchedule, opts metav1.CreateOptions) (*v1.BackupSchedule, error) {
	ret := _m.Called(ctx, backupSchedule, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BackupSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) (*v1.BackupSchedule, error)); ok {
		return rf(ctx, backupSchedule, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) *v1.BackupSchedule); ok {
		r0 = rf(ctx, backupSchedule, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BackupSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, backupSchedule, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupScheduleClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockBackupScheduleClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - backupSchedule *v1.BackupSchedule
//   - opts metav1.CreateOptions
func (_e *mockBackupScheduleClient_Expecter) Create(ctx interface{}, backupSchedule interface{}, opts interface{}) *mockBackupScheduleClient_Create_Call {
	return &mockBackupScheduleClient_Create_Call{Call: _e.mock.On("Create", ctx, backupSchedule, opts)}
}

func (_c *mockBackupScheduleClient_Create_Call) Run(run func(ctx context.Context, backupSchedule *v1.BackupSchedule, opts metav1.CreateOptions)) *mockBackupScheduleClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockBackupScheduleClient_Create_Call) Return(_a0 *v1.BackupSchedule, _a1 error) *mockBackupScheduleClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupScheduleClient_Create_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) (*v1.BackupSchedule, error)) *mockBackupScheduleClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockBackupScheduleClient) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackupScheduleClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockBackupScheduleClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockBackupScheduleClient_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockBackupScheduleClient_Delete_Call {
	return &mockBackupScheduleClient_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockBackupScheduleClient_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockBackupScheduleClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockBackupScheduleClient_Delete_Call) Return(_a0 error) *mockBackupScheduleClient_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackupScheduleClient_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockBackupScheduleClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockBackupScheduleClient) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupScheduleClient_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockBackupScheduleClient_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockBackupScheduleClient_Expecter) Watch(ctx interface{}, opts interface{}) *mockBackupScheduleClient_Watch_Call {
	return &mockBackupScheduleClient_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockBackupScheduleClient_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockBackupScheduleClient_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockBackupScheduleClient_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockBackupScheduleClient_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupScheduleClient_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *mockBackupScheduleClient_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBackupScheduleClient creates a new instance of mockBackupScheduleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBackupScheduleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBackupScheduleClient {
	mock := &mockBackupScheduleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
