// Code generated by mockery v2.53.3. DO NOT EDIT.

package configuration

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// mockGlobalConfigImporter is an autogenerated mock type for the globalConfigImporter type
type mockGlobalConfigImporter struct {
	mock.Mock
}

type mockGlobalConfigImporter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGlobalConfigImporter) EXPECT() *mockGlobalConfigImporter_Expecter {
	return &mockGlobalConfigImporter_Expecter{mock: &_m.Mock}
}

// backupGlobalConfigByKeys provides a mock function with given fields: ctx, keys, backupType
func (_m *mockGlobalConfigImporter) backupGlobalConfigByKeys(ctx context.Context, keys []string, backupType BackupType) error {
	ret := _m.Called(ctx, keys, backupType)

	if len(ret) == 0 {
		panic("no return value specified for backupGlobalConfigByKeys")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, BackupType) error); ok {
		r0 = rf(ctx, keys, backupType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockGlobalConfigImporter_backupGlobalConfigByKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'backupGlobalConfigByKeys'
type mockGlobalConfigImporter_backupGlobalConfigByKeys_Call struct {
	*mock.Call
}

// backupGlobalConfigByKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
//   - backupType BackupType
func (_e *mockGlobalConfigImporter_Expecter) backupGlobalConfigByKeys(ctx interface{}, keys interface{}, backupType interface{}) *mockGlobalConfigImporter_backupGlobalConfigByKeys_Call {
	return &mockGlobalConfigImporter_backupGlobalConfigByKeys_Call{Call: _e.mock.On("backupGlobalConfigByKeys", ctx, keys, backupType)}
}

func (_c *mockGlobalConfigImporter_backupGlobalConfigByKeys_Call) Run(run func(ctx context.Context, keys []string, backupType BackupType)) *mockGlobalConfigImporter_backupGlobalConfigByKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(BackupType))
	})
	return _c
}

func (_c *mockGlobalConfigImporter_backupGlobalConfigByKeys_Call) Return(_a0 error) *mockGlobalConfigImporter_backupGlobalConfigByKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockGlobalConfigImporter_backupGlobalConfigByKeys_Call) RunAndReturn(run func(context.Context, []string, BackupType) error) *mockGlobalConfigImporter_backupGlobalConfigByKeys_Call {
	_c.Call.Return(run)
	return _c
}

// importGlobalCertificates provides a mock function with given fields: ctx, config
func (_m *mockGlobalConfigImporter) importGlobalCertificates(ctx context.Context, config globalConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for importGlobalCertificates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, globalConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockGlobalConfigImporter_importGlobalCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'importGlobalCertificates'
type mockGlobalConfigImporter_importGlobalCertificates_Call struct {
	*mock.Call
}

// importGlobalCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - config globalConfig
func (_e *mockGlobalConfigImporter_Expecter) importGlobalCertificates(ctx interface{}, config interface{}) *mockGlobalConfigImporter_importGlobalCertificates_Call {
	return &mockGlobalConfigImporter_importGlobalCertificates_Call{Call: _e.mock.On("importGlobalCertificates", ctx, config)}
}

func (_c *mockGlobalConfigImporter_importGlobalCertificates_Call) Run(run func(ctx context.Context, config globalConfig)) *mockGlobalConfigImporter_importGlobalCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(globalConfig))
	})
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalCertificates_Call) Return(_a0 error) *mockGlobalConfigImporter_importGlobalCertificates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalCertificates_Call) RunAndReturn(run func(context.Context, globalConfig) error) *mockGlobalConfigImporter_importGlobalCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// importGlobalConfig provides a mock function with given fields: ctx, config
func (_m *mockGlobalConfigImporter) importGlobalConfig(ctx context.Context, config exporter.GlobalConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for importGlobalConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, exporter.GlobalConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockGlobalConfigImporter_importGlobalConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'importGlobalConfig'
type mockGlobalConfigImporter_importGlobalConfig_Call struct {
	*mock.Call
}

// importGlobalConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config exporter.GlobalConfig
func (_e *mockGlobalConfigImporter_Expecter) importGlobalConfig(ctx interface{}, config interface{}) *mockGlobalConfigImporter_importGlobalConfig_Call {
	return &mockGlobalConfigImporter_importGlobalConfig_Call{Call: _e.mock.On("importGlobalConfig", ctx, config)}
}

func (_c *mockGlobalConfigImporter_importGlobalConfig_Call) Run(run func(ctx context.Context, config exporter.GlobalConfig)) *mockGlobalConfigImporter_importGlobalConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(exporter.GlobalConfig))
	})
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalConfig_Call) Return(_a0 error) *mockGlobalConfigImporter_importGlobalConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalConfig_Call) RunAndReturn(run func(context.Context, exporter.GlobalConfig) error) *mockGlobalConfigImporter_importGlobalConfig_Call {
	_c.Call.Return(run)
	return _c
}

// importGlobalFQDN provides a mock function with given fields: ctx, config
func (_m *mockGlobalConfigImporter) importGlobalFQDN(ctx context.Context, config globalConfig) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for importGlobalFQDN")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, globalConfig) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockGlobalConfigImporter_importGlobalFQDN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'importGlobalFQDN'
type mockGlobalConfigImporter_importGlobalFQDN_Call struct {
	*mock.Call
}

// importGlobalFQDN is a helper method to define mock.On call
//   - ctx context.Context
//   - config globalConfig
func (_e *mockGlobalConfigImporter_Expecter) importGlobalFQDN(ctx interface{}, config interface{}) *mockGlobalConfigImporter_importGlobalFQDN_Call {
	return &mockGlobalConfigImporter_importGlobalFQDN_Call{Call: _e.mock.On("importGlobalFQDN", ctx, config)}
}

func (_c *mockGlobalConfigImporter_importGlobalFQDN_Call) Run(run func(ctx context.Context, config globalConfig)) *mockGlobalConfigImporter_importGlobalFQDN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(globalConfig))
	})
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalFQDN_Call) Return(_a0 error) *mockGlobalConfigImporter_importGlobalFQDN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockGlobalConfigImporter_importGlobalFQDN_Call) RunAndReturn(run func(context.Context, globalConfig) error) *mockGlobalConfigImporter_importGlobalFQDN_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGlobalConfigImporter creates a new instance of mockGlobalConfigImporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGlobalConfigImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGlobalConfigImporter {
	mock := &mockGlobalConfigImporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
