// Code generated by mockery v2.53.3. DO NOT EDIT.

package configuration

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// mockBackupScheduleImporter is an autogenerated mock type for the backupScheduleImporter type
type mockBackupScheduleImporter struct {
	mock.Mock
}

type mockBackupScheduleImporter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBackupScheduleImporter) EXPECT() *mockBackupScheduleImporter_Expecter {
	return &mockBackupScheduleImporter_Expecter{mock: &_m.Mock}
}

// importBackupSchedules provides a mock function with given fields: ctx, config
func (_m *mockBackupScheduleImporter) importBackupSchedules(ctx context.Context, config []exporter.BackupSchedule) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for importBackupSchedules")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []exporter.BackupSchedule) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackupScheduleImporter_importBackupSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'importBackupSchedules'
type mockBackupScheduleImporter_importBackupSchedules_Call struct {
	*mock.Call
}

// importBackupSchedules is a helper method to define mock.On call
//   - ctx context.Context
//   - config []exporter.BackupSchedule
func (_e *mockBackupScheduleImporter_Expecter) importBackupSchedules(ctx interface{}, config interface{}) *mockBackupScheduleImporter_importBackupSchedules_Call {
	return &mockBackupScheduleImporter_importBackupSchedules_Call{Call: _e.mock.On("importBackupSchedules", ctx, config)}
}

func (_c *mockBackupScheduleImporter_importBackupSchedules_Call) Run(run func(ctx context.Context, config []exporter.BackupSchedule)) *mockBackupScheduleImporter_importBackupSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]exporter.BackupSchedule))
	})
	return _c
}

func (_c *mockBackupScheduleImporter_importBackupSchedules_Call) Return(_a0 error) *mockBackupScheduleImporter_importBackupSchedules_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackupScheduleImporter_importBackupSchedules_Call) RunAndReturn(run func(context.Context, []exporter.BackupSchedule) error) *mockBackupScheduleImporter_importBackupSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBackupScheduleImporter creates a new instance of mockBackupScheduleImporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBackupScheduleImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBackupScheduleImporter {
	mock := &mockBackupScheduleImporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
