// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockFqdnChanger is an autogenerated mock type for the fqdnChanger type
type mockFqdnChanger struct {
	mock.Mock
}

type mockFqdnChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFqdnChanger) EXPECT() *mockFqdnChanger_Expecter {
	return &mockFqdnChanger_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function with given fields: ctx
func (_m *mockFqdnChanger) Backup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFqdnChanger_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type mockFqdnChanger_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockFqdnChanger_Expecter) Backup(ctx interface{}) *mockFqdnChanger_Backup_Call {
	return &mockFqdnChanger_Backup_Call{Call: _e.mock.On("Backup", ctx)}
}

func (_c *mockFqdnChanger_Backup_Call) Run(run func(ctx context.Context)) *mockFqdnChanger_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockFqdnChanger_Backup_Call) Return(_a0 error) *mockFqdnChanger_Backup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFqdnChanger_Backup_Call) RunAndReturn(run func(context.Context) error) *mockFqdnChanger_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBackup provides a mock function with given fields: ctx
func (_m *mockFqdnChanger) DeleteBackup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFqdnChanger_DeleteBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBackup'
type mockFqdnChanger_DeleteBackup_Call struct {
	*mock.Call
}

// DeleteBackup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockFqdnChanger_Expecter) DeleteBackup(ctx interface{}) *mockFqdnChanger_DeleteBackup_Call {
	return &mockFqdnChanger_DeleteBackup_Call{Call: _e.mock.On("DeleteBackup", ctx)}
}

func (_c *mockFqdnChanger_DeleteBackup_Call) Run(run func(ctx context.Context)) *mockFqdnChanger_DeleteBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockFqdnChanger_DeleteBackup_Call) Return(_a0 error) *mockFqdnChanger_DeleteBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFqdnChanger_DeleteBackup_Call) RunAndReturn(run func(context.Context) error) *mockFqdnChanger_DeleteBackup_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx
func (_m *mockFqdnChanger) Restore(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFqdnChanger_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type mockFqdnChanger_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockFqdnChanger_Expecter) Restore(ctx interface{}) *mockFqdnChanger_Restore_Call {
	return &mockFqdnChanger_Restore_Call{Call: _e.mock.On("Restore", ctx)}
}

func (_c *mockFqdnChanger_Restore_Call) Run(run func(ctx context.Context)) *mockFqdnChanger_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockFqdnChanger_Restore_Call) Return(_a0 error) *mockFqdnChanger_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFqdnChanger_Restore_Call) RunAndReturn(run func(context.Context) error) *mockFqdnChanger_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, c
func (_m *mockFqdnChanger) Update(ctx context.Context, c ConfigChange) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ConfigChange) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFqdnChanger_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockFqdnChanger_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c ConfigChange
func (_e *mockFqdnChanger_Expecter) Update(ctx interface{}, c interface{}) *mockFqdnChanger_Update_Call {
	return &mockFqdnChanger_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *mockFqdnChanger_Update_Call) Run(run func(ctx context.Context, c ConfigChange)) *mockFqdnChanger_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ConfigChange))
	})
	return _c
}

func (_c *mockFqdnChanger_Update_Call) Return(_a0 error) *mockFqdnChanger_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFqdnChanger_Update_Call) RunAndReturn(run func(context.Context, ConfigChange) error) *mockFqdnChanger_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFqdnChanger creates a new instance of mockFqdnChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFqdnChanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFqdnChanger {
	mock := &mockFqdnChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
