// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockFqdnUpdater is an autogenerated mock type for the fqdnUpdater type
type mockFqdnUpdater struct {
	mock.Mock
}

type mockFqdnUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFqdnUpdater) EXPECT() *mockFqdnUpdater_Expecter {
	return &mockFqdnUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: ctx, c
func (_m *mockFqdnUpdater) Update(ctx context.Context, c ConfigChange) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ConfigChange) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFqdnUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockFqdnUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c ConfigChange
func (_e *mockFqdnUpdater_Expecter) Update(ctx interface{}, c interface{}) *mockFqdnUpdater_Update_Call {
	return &mockFqdnUpdater_Update_Call{Call: _e.mock.On("Update", ctx, c)}
}

func (_c *mockFqdnUpdater_Update_Call) Run(run func(ctx context.Context, c ConfigChange)) *mockFqdnUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ConfigChange))
	})
	return _c
}

func (_c *mockFqdnUpdater_Update_Call) Return(_a0 error) *mockFqdnUpdater_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFqdnUpdater_Update_Call) RunAndReturn(run func(context.Context, ConfigChange) error) *mockFqdnUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFqdnUpdater creates a new instance of mockFqdnUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFqdnUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFqdnUpdater {
	mock := &mockFqdnUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
