// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "k8s.io/api/core/v1"
)

// mockConfigMapRepository is an autogenerated mock type for the configMapRepository type
type mockConfigMapRepository struct {
	mock.Mock
}

type mockConfigMapRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigMapRepository) EXPECT() *mockConfigMapRepository_Expecter {
	return &mockConfigMapRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, configMap, opts
func (_m *mockConfigMapRepository) Create(ctx context.Context, configMap *v1.ConfigMap, opts metav1.CreateOptions) (*v1.ConfigMap, error) {
	ret := _m.Called(ctx, configMap, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap, metav1.CreateOptions) (*v1.ConfigMap, error)); ok {
		return rf(ctx, configMap, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap, metav1.CreateOptions) *v1.ConfigMap); ok {
		r0 = rf(ctx, configMap, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ConfigMap, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, configMap, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigMapRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockConfigMapRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - configMap *v1.ConfigMap
//   - opts metav1.CreateOptions
func (_e *mockConfigMapRepository_Expecter) Create(ctx interface{}, configMap interface{}, opts interface{}) *mockConfigMapRepository_Create_Call {
	return &mockConfigMapRepository_Create_Call{Call: _e.mock.On("Create", ctx, configMap, opts)}
}

func (_c *mockConfigMapRepository_Create_Call) Run(run func(ctx context.Context, configMap *v1.ConfigMap, opts metav1.CreateOptions)) *mockConfigMapRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.ConfigMap), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockConfigMapRepository_Create_Call) Return(_a0 *v1.ConfigMap, _a1 error) *mockConfigMapRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigMapRepository_Create_Call) RunAndReturn(run func(context.Context, *v1.ConfigMap, metav1.CreateOptions) (*v1.ConfigMap, error)) *mockConfigMapRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockConfigMapRepository) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockConfigMapRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockConfigMapRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockConfigMapRepository_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockConfigMapRepository_Delete_Call {
	return &mockConfigMapRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockConfigMapRepository_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockConfigMapRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockConfigMapRepository_Delete_Call) Return(_a0 error) *mockConfigMapRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConfigMapRepository_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockConfigMapRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockConfigMapRepository) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ConfigMap, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.ConfigMap, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.ConfigMap); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigMapRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockConfigMapRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockConfigMapRepository_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockConfigMapRepository_Get_Call {
	return &mockConfigMapRepository_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockConfigMapRepository_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockConfigMapRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockConfigMapRepository_Get_Call) Return(_a0 *v1.ConfigMap, _a1 error) *mockConfigMapRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigMapRepository_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.ConfigMap, error)) *mockConfigMapRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, configMap, opts
func (_m *mockConfigMapRepository) Update(ctx context.Context, configMap *v1.ConfigMap, opts metav1.UpdateOptions) (*v1.ConfigMap, error) {
	ret := _m.Called(ctx, configMap, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap, metav1.UpdateOptions) (*v1.ConfigMap, error)); ok {
		return rf(ctx, configMap, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ConfigMap, metav1.UpdateOptions) *v1.ConfigMap); ok {
		r0 = rf(ctx, configMap, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ConfigMap, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, configMap, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigMapRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockConfigMapRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - configMap *v1.ConfigMap
//   - opts metav1.UpdateOptions
func (_e *mockConfigMapRepository_Expecter) Update(ctx interface{}, configMap interface{}, opts interface{}) *mockConfigMapRepository_Update_Call {
	return &mockConfigMapRepository_Update_Call{Call: _e.mock.On("Update", ctx, configMap, opts)}
}

func (_c *mockConfigMapRepository_Update_Call) Run(run func(ctx context.Context, configMap *v1.ConfigMap, opts metav1.UpdateOptions)) *mockConfigMapRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.ConfigMap), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockConfigMapRepository_Update_Call) Return(_a0 *v1.ConfigMap, _a1 error) *mockConfigMapRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigMapRepository_Update_Call) RunAndReturn(run func(context.Context, *v1.ConfigMap, metav1.UpdateOptions) (*v1.ConfigMap, error)) *mockConfigMapRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigMapRepository creates a new instance of mockConfigMapRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigMapRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigMapRepository {
	mock := &mockConfigMapRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
