// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockSecretRepository is an autogenerated mock type for the secretRepository type
type mockSecretRepository struct {
	mock.Mock
}

type mockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSecretRepository) EXPECT() *mockSecretRepository_Expecter {
	return &mockSecretRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, secret, opts
func (_m *mockSecretRepository) Create(ctx context.Context, secret *v1.Secret, opts metav1.CreateOptions) (*v1.Secret, error) {
	ret := _m.Called(ctx, secret, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Secret, metav1.CreateOptions) (*v1.Secret, error)); ok {
		return rf(ctx, secret, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Secret, metav1.CreateOptions) *v1.Secret); ok {
		r0 = rf(ctx, secret, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Secret, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, secret, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockSecretRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *v1.Secret
//   - opts metav1.CreateOptions
func (_e *mockSecretRepository_Expecter) Create(ctx interface{}, secret interface{}, opts interface{}) *mockSecretRepository_Create_Call {
	return &mockSecretRepository_Create_Call{Call: _e.mock.On("Create", ctx, secret, opts)}
}

func (_c *mockSecretRepository_Create_Call) Run(run func(ctx context.Context, secret *v1.Secret, opts metav1.CreateOptions)) *mockSecretRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Secret), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockSecretRepository_Create_Call) Return(_a0 *v1.Secret, _a1 error) *mockSecretRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretRepository_Create_Call) RunAndReturn(run func(context.Context, *v1.Secret, metav1.CreateOptions) (*v1.Secret, error)) *mockSecretRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockSecretRepository) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSecretRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockSecretRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockSecretRepository_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockSecretRepository_Delete_Call {
	return &mockSecretRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockSecretRepository_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockSecretRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockSecretRepository_Delete_Call) Return(_a0 error) *mockSecretRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSecretRepository_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockSecretRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockSecretRepository) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Secret, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.Secret, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.Secret); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockSecretRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockSecretRepository_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockSecretRepository_Get_Call {
	return &mockSecretRepository_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockSecretRepository_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockSecretRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockSecretRepository_Get_Call) Return(_a0 *v1.Secret, _a1 error) *mockSecretRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretRepository_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.Secret, error)) *mockSecretRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, secret, opts
func (_m *mockSecretRepository) Update(ctx context.Context, secret *v1.Secret, opts metav1.UpdateOptions) (*v1.Secret, error) {
	ret := _m.Called(ctx, secret, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Secret, metav1.UpdateOptions) (*v1.Secret, error)); ok {
		return rf(ctx, secret, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Secret, metav1.UpdateOptions) *v1.Secret); ok {
		r0 = rf(ctx, secret, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Secret, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, secret, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSecretRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockSecretRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *v1.Secret
//   - opts metav1.UpdateOptions
func (_e *mockSecretRepository_Expecter) Update(ctx interface{}, secret interface{}, opts interface{}) *mockSecretRepository_Update_Call {
	return &mockSecretRepository_Update_Call{Call: _e.mock.On("Update", ctx, secret, opts)}
}

func (_c *mockSecretRepository_Update_Call) Run(run func(ctx context.Context, secret *v1.Secret, opts metav1.UpdateOptions)) *mockSecretRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Secret), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockSecretRepository_Update_Call) Return(_a0 *v1.Secret, _a1 error) *mockSecretRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSecretRepository_Update_Call) RunAndReturn(run func(context.Context, *v1.Secret, metav1.UpdateOptions) (*v1.Secret, error)) *mockSecretRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSecretRepository creates a new instance of mockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSecretRepository {
	mock := &mockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
