// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockCertificateUpdater is an autogenerated mock type for the certificateUpdater type
type mockCertificateUpdater struct {
	mock.Mock
}

type mockCertificateUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCertificateUpdater) EXPECT() *mockCertificateUpdater_Expecter {
	return &mockCertificateUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: ctx, tlsKeyPair
func (_m *mockCertificateUpdater) Update(ctx context.Context, tlsKeyPair SecretChange) error {
	ret := _m.Called(ctx, tlsKeyPair)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, SecretChange) error); ok {
		r0 = rf(ctx, tlsKeyPair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCertificateUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockCertificateUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tlsKeyPair SecretChange
func (_e *mockCertificateUpdater_Expecter) Update(ctx interface{}, tlsKeyPair interface{}) *mockCertificateUpdater_Update_Call {
	return &mockCertificateUpdater_Update_Call{Call: _e.mock.On("Update", ctx, tlsKeyPair)}
}

func (_c *mockCertificateUpdater_Update_Call) Run(run func(ctx context.Context, tlsKeyPair SecretChange)) *mockCertificateUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(SecretChange))
	})
	return _c
}

func (_c *mockCertificateUpdater_Update_Call) Return(_a0 error) *mockCertificateUpdater_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCertificateUpdater_Update_Call) RunAndReturn(run func(context.Context, SecretChange) error) *mockCertificateUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCertificateUpdater creates a new instance of mockCertificateUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCertificateUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCertificateUpdater {
	mock := &mockCertificateUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
