// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockCertificateChanger is an autogenerated mock type for the certificateChanger type
type mockCertificateChanger struct {
	mock.Mock
}

type mockCertificateChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCertificateChanger) EXPECT() *mockCertificateChanger_Expecter {
	return &mockCertificateChanger_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function with given fields: ctx
func (_m *mockCertificateChanger) Backup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCertificateChanger_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type mockCertificateChanger_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockCertificateChanger_Expecter) Backup(ctx interface{}) *mockCertificateChanger_Backup_Call {
	return &mockCertificateChanger_Backup_Call{Call: _e.mock.On("Backup", ctx)}
}

func (_c *mockCertificateChanger_Backup_Call) Run(run func(ctx context.Context)) *mockCertificateChanger_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockCertificateChanger_Backup_Call) Return(_a0 error) *mockCertificateChanger_Backup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCertificateChanger_Backup_Call) RunAndReturn(run func(context.Context) error) *mockCertificateChanger_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBackup provides a mock function with given fields: ctx
func (_m *mockCertificateChanger) DeleteBackup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCertificateChanger_DeleteBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBackup'
type mockCertificateChanger_DeleteBackup_Call struct {
	*mock.Call
}

// DeleteBackup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockCertificateChanger_Expecter) DeleteBackup(ctx interface{}) *mockCertificateChanger_DeleteBackup_Call {
	return &mockCertificateChanger_DeleteBackup_Call{Call: _e.mock.On("DeleteBackup", ctx)}
}

func (_c *mockCertificateChanger_DeleteBackup_Call) Run(run func(ctx context.Context)) *mockCertificateChanger_DeleteBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockCertificateChanger_DeleteBackup_Call) Return(_a0 error) *mockCertificateChanger_DeleteBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCertificateChanger_DeleteBackup_Call) RunAndReturn(run func(context.Context) error) *mockCertificateChanger_DeleteBackup_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx
func (_m *mockCertificateChanger) Restore(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCertificateChanger_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type mockCertificateChanger_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockCertificateChanger_Expecter) Restore(ctx interface{}) *mockCertificateChanger_Restore_Call {
	return &mockCertificateChanger_Restore_Call{Call: _e.mock.On("Restore", ctx)}
}

func (_c *mockCertificateChanger_Restore_Call) Run(run func(ctx context.Context)) *mockCertificateChanger_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockCertificateChanger_Restore_Call) Return(_a0 error) *mockCertificateChanger_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCertificateChanger_Restore_Call) RunAndReturn(run func(context.Context) error) *mockCertificateChanger_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tlsKeyPair
func (_m *mockCertificateChanger) Update(ctx context.Context, tlsKeyPair SecretChange) error {
	ret := _m.Called(ctx, tlsKeyPair)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, SecretChange) error); ok {
		r0 = rf(ctx, tlsKeyPair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCertificateChanger_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockCertificateChanger_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tlsKeyPair SecretChange
func (_e *mockCertificateChanger_Expecter) Update(ctx interface{}, tlsKeyPair interface{}) *mockCertificateChanger_Update_Call {
	return &mockCertificateChanger_Update_Call{Call: _e.mock.On("Update", ctx, tlsKeyPair)}
}

func (_c *mockCertificateChanger_Update_Call) Run(run func(ctx context.Context, tlsKeyPair SecretChange)) *mockCertificateChanger_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(SecretChange))
	})
	return _c
}

func (_c *mockCertificateChanger_Update_Call) Return(_a0 error) *mockCertificateChanger_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCertificateChanger_Update_Call) RunAndReturn(run func(context.Context, SecretChange) error) *mockCertificateChanger_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCertificateChanger creates a new instance of mockCertificateChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCertificateChanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCertificateChanger {
	mock := &mockCertificateChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
