// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockBackuper is an autogenerated mock type for the backuper type
type mockBackuper struct {
	mock.Mock
}

type mockBackuper_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBackuper) EXPECT() *mockBackuper_Expecter {
	return &mockBackuper_Expecter{mock: &_m.Mock}
}

// Backup provides a mock function with given fields: ctx
func (_m *mockBackuper) Backup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Backup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackuper_Backup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backup'
type mockBackuper_Backup_Call struct {
	*mock.Call
}

// Backup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockBackuper_Expecter) Backup(ctx interface{}) *mockBackuper_Backup_Call {
	return &mockBackuper_Backup_Call{Call: _e.mock.On("Backup", ctx)}
}

func (_c *mockBackuper_Backup_Call) Run(run func(ctx context.Context)) *mockBackuper_Backup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockBackuper_Backup_Call) Return(_a0 error) *mockBackuper_Backup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackuper_Backup_Call) RunAndReturn(run func(context.Context) error) *mockBackuper_Backup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBackup provides a mock function with given fields: ctx
func (_m *mockBackuper) DeleteBackup(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBackup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackuper_DeleteBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBackup'
type mockBackuper_DeleteBackup_Call struct {
	*mock.Call
}

// DeleteBackup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockBackuper_Expecter) DeleteBackup(ctx interface{}) *mockBackuper_DeleteBackup_Call {
	return &mockBackuper_DeleteBackup_Call{Call: _e.mock.On("DeleteBackup", ctx)}
}

func (_c *mockBackuper_DeleteBackup_Call) Run(run func(ctx context.Context)) *mockBackuper_DeleteBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockBackuper_DeleteBackup_Call) Return(_a0 error) *mockBackuper_DeleteBackup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackuper_DeleteBackup_Call) RunAndReturn(run func(context.Context) error) *mockBackuper_DeleteBackup_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBackuper creates a new instance of mockBackuper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBackuper(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBackuper {
	mock := &mockBackuper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
