// Code generated by mockery v2.53.3. DO NOT EDIT.

package fqdn

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockRestorer is an autogenerated mock type for the restorer type
type mockRestorer struct {
	mock.Mock
}

type mockRestorer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRestorer) EXPECT() *mockRestorer_Expecter {
	return &mockRestorer_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function with given fields: ctx
func (_m *mockRestorer) Restore(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRestorer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type mockRestorer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRestorer_Expecter) Restore(ctx interface{}) *mockRestorer_Restore_Call {
	return &mockRestorer_Restore_Call{Call: _e.mock.On("Restore", ctx)}
}

func (_c *mockRestorer_Restore_Call) Run(run func(ctx context.Context)) *mockRestorer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockRestorer_Restore_Call) Return(_a0 error) *mockRestorer_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRestorer_Restore_Call) RunAndReturn(run func(context.Context) error) *mockRestorer_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRestorer creates a new instance of mockRestorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRestorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRestorer {
	mock := &mockRestorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
