// Code generated by mockery v2.53.3. DO NOT EDIT.

package cron

import (
	tasker "github.com/adhocore/gronx/pkg/tasker"
	mock "github.com/stretchr/testify/mock"
)

// mockNewTaskerFunc is an autogenerated mock type for the newTaskerFunc type
type mockNewTaskerFunc struct {
	mock.Mock
}

type mockNewTaskerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockNewTaskerFunc) EXPECT() *mockNewTaskerFunc_Expecter {
	return &mockNewTaskerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: opt
func (_m *mockNewTaskerFunc) Execute(opt tasker.Option) taskRunner {
	ret := _m.Called(opt)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 taskRunner
	if rf, ok := ret.Get(0).(func(tasker.Option) taskRunner); ok {
		r0 = rf(opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(taskRunner)
		}
	}

	return r0
}

// mockNewTaskerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockNewTaskerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - opt tasker.Option
func (_e *mockNewTaskerFunc_Expecter) Execute(opt interface{}) *mockNewTaskerFunc_Execute_Call {
	return &mockNewTaskerFunc_Execute_Call{Call: _e.mock.On("Execute", opt)}
}

func (_c *mockNewTaskerFunc_Execute_Call) Run(run func(opt tasker.Option)) *mockNewTaskerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tasker.Option))
	})
	return _c
}

func (_c *mockNewTaskerFunc_Execute_Call) Return(_a0 taskRunner) *mockNewTaskerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockNewTaskerFunc_Execute_Call) RunAndReturn(run func(tasker.Option) taskRunner) *mockNewTaskerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockNewTaskerFunc creates a new instance of mockNewTaskerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockNewTaskerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockNewTaskerFunc {
	mock := &mockNewTaskerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
