// Code generated by mockery v2.53.3. DO NOT EDIT.

package cron

import (
	tasker "github.com/adhocore/gronx/pkg/tasker"
	mock "github.com/stretchr/testify/mock"
)

// mockTaskRunner is an autogenerated mock type for the taskRunner type
type mockTaskRunner struct {
	mock.Mock
}

type mockTaskRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTaskRunner) EXPECT() *mockTaskRunner_Expecter {
	return &mockTaskRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *mockTaskRunner) Run() {
	_m.Called()
}

// mockTaskRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type mockTaskRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *mockTaskRunner_Expecter) Run() *mockTaskRunner_Run_Call {
	return &mockTaskRunner_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *mockTaskRunner_Run_Call) Run(run func()) *mockTaskRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTaskRunner_Run_Call) Return() *mockTaskRunner_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockTaskRunner_Run_Call) RunAndReturn(run func()) *mockTaskRunner_Run_Call {
	_c.Run(run)
	return _c
}

// Running provides a mock function with no fields
func (_m *mockTaskRunner) Running() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Running")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// mockTaskRunner_Running_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Running'
type mockTaskRunner_Running_Call struct {
	*mock.Call
}

// Running is a helper method to define mock.On call
func (_e *mockTaskRunner_Expecter) Running() *mockTaskRunner_Running_Call {
	return &mockTaskRunner_Running_Call{Call: _e.mock.On("Running")}
}

func (_c *mockTaskRunner_Running_Call) Run(run func()) *mockTaskRunner_Running_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTaskRunner_Running_Call) Return(_a0 bool) *mockTaskRunner_Running_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTaskRunner_Running_Call) RunAndReturn(run func() bool) *mockTaskRunner_Running_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *mockTaskRunner) Stop() {
	_m.Called()
}

// mockTaskRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type mockTaskRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *mockTaskRunner_Expecter) Stop() *mockTaskRunner_Stop_Call {
	return &mockTaskRunner_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *mockTaskRunner_Stop_Call) Run(run func()) *mockTaskRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTaskRunner_Stop_Call) Return() *mockTaskRunner_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockTaskRunner_Stop_Call) RunAndReturn(run func()) *mockTaskRunner_Stop_Call {
	_c.Run(run)
	return _c
}

// Task provides a mock function with given fields: expr, task, concurrent
func (_m *mockTaskRunner) Task(expr string, task tasker.TaskFunc, concurrent ...bool) *tasker.Tasker {
	_va := make([]interface{}, len(concurrent))
	for _i := range concurrent {
		_va[_i] = concurrent[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, expr, task)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Task")
	}

	var r0 *tasker.Tasker
	if rf, ok := ret.Get(0).(func(string, tasker.TaskFunc, ...bool) *tasker.Tasker); ok {
		r0 = rf(expr, task, concurrent...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasker.Tasker)
		}
	}

	return r0
}

// mockTaskRunner_Task_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Task'
type mockTaskRunner_Task_Call struct {
	*mock.Call
}

// Task is a helper method to define mock.On call
//   - expr string
//   - task tasker.TaskFunc
//   - concurrent ...bool
func (_e *mockTaskRunner_Expecter) Task(expr interface{}, task interface{}, concurrent ...interface{}) *mockTaskRunner_Task_Call {
	return &mockTaskRunner_Task_Call{Call: _e.mock.On("Task",
		append([]interface{}{expr, task}, concurrent...)...)}
}

func (_c *mockTaskRunner_Task_Call) Run(run func(expr string, task tasker.TaskFunc, concurrent ...bool)) *mockTaskRunner_Task_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]bool, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(bool)
			}
		}
		run(args[0].(string), args[1].(tasker.TaskFunc), variadicArgs...)
	})
	return _c
}

func (_c *mockTaskRunner_Task_Call) Return(_a0 *tasker.Tasker) *mockTaskRunner_Task_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTaskRunner_Task_Call) RunAndReturn(run func(string, tasker.TaskFunc, ...bool) *tasker.Tasker) *mockTaskRunner_Task_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTaskRunner creates a new instance of mockTaskRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTaskRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTaskRunner {
	mock := &mockTaskRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
