// Code generated by mockery v2.53.3. DO NOT EDIT.

package cron

import (
	tasker "github.com/adhocore/gronx/pkg/tasker"
	mock "github.com/stretchr/testify/mock"
)

// MocknewTaskerFunc is an autogenerated mock type for the newTaskerFunc type
type MocknewTaskerFunc struct {
	mock.Mock
}

type MocknewTaskerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MocknewTaskerFunc) EXPECT() *MocknewTaskerFunc_Expecter {
	return &MocknewTaskerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: opt
func (_m *MocknewTaskerFunc) Execute(opt tasker.Option) taskRunner {
	ret := _m.Called(opt)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 taskRunner
	if rf, ok := ret.Get(0).(func(tasker.Option) taskRunner); ok {
		r0 = rf(opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(taskRunner)
		}
	}

	return r0
}

// MocknewTaskerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MocknewTaskerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - opt tasker.Option
func (_e *MocknewTaskerFunc_Expecter) Execute(opt interface{}) *MocknewTaskerFunc_Execute_Call {
	return &MocknewTaskerFunc_Execute_Call{Call: _e.mock.On("Execute", opt)}
}

func (_c *MocknewTaskerFunc_Execute_Call) Run(run func(opt tasker.Option)) *MocknewTaskerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tasker.Option))
	})
	return _c
}

func (_c *MocknewTaskerFunc_Execute_Call) Return(_a0 taskRunner) *MocknewTaskerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocknewTaskerFunc_Execute_Call) RunAndReturn(run func(tasker.Option) taskRunner) *MocknewTaskerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocknewTaskerFunc creates a new instance of MocknewTaskerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocknewTaskerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocknewTaskerFunc {
	mock := &MocknewTaskerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
