// Code generated by mockery v2.53.3. DO NOT EDIT.

package sync

import (
	context "context"

	migration "github.com/cloudogu/ces-importer/migration"
	mock "github.com/stretchr/testify/mock"
)

// mockSystemInfoProvider is an autogenerated mock type for the systemInfoProvider type
type mockSystemInfoProvider struct {
	mock.Mock
}

type mockSystemInfoProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSystemInfoProvider) EXPECT() *mockSystemInfoProvider_Expecter {
	return &mockSystemInfoProvider_Expecter{mock: &_m.Mock}
}

// GetSystemInfo provides a mock function with given fields: ctx
func (_m *mockSystemInfoProvider) GetSystemInfo(ctx context.Context) (*migration.SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemInfo")
	}

	var r0 *migration.SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*migration.SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *migration.SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*migration.SystemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSystemInfoProvider_GetSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemInfo'
type mockSystemInfoProvider_GetSystemInfo_Call struct {
	*mock.Call
}

// GetSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSystemInfoProvider_Expecter) GetSystemInfo(ctx interface{}) *mockSystemInfoProvider_GetSystemInfo_Call {
	return &mockSystemInfoProvider_GetSystemInfo_Call{Call: _e.mock.On("GetSystemInfo", ctx)}
}

func (_c *mockSystemInfoProvider_GetSystemInfo_Call) Run(run func(ctx context.Context)) *mockSystemInfoProvider_GetSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockSystemInfoProvider_GetSystemInfo_Call) Return(systemInfo *migration.SystemInfo, err error) *mockSystemInfoProvider_GetSystemInfo_Call {
	_c.Call.Return(systemInfo, err)
	return _c
}

func (_c *mockSystemInfoProvider_GetSystemInfo_Call) RunAndReturn(run func(context.Context) (*migration.SystemInfo, error)) *mockSystemInfoProvider_GetSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSystemInfoProvider creates a new instance of mockSystemInfoProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSystemInfoProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSystemInfoProvider {
	mock := &mockSystemInfoProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
