// Code generated by mockery v2.53.3. DO NOT EDIT.

package sync

import mock "github.com/stretchr/testify/mock"

// mockCommandMaker is an autogenerated mock type for the commandMaker type
type mockCommandMaker struct {
	mock.Mock
}

type mockCommandMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCommandMaker) EXPECT() *mockCommandMaker_Expecter {
	return &mockCommandMaker_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name, arg
func (_m *mockCommandMaker) Execute(name string, arg ...string) command {
	_va := make([]interface{}, len(arg))
	for _i := range arg {
		_va[_i] = arg[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 command
	if rf, ok := ret.Get(0).(func(string, ...string) command); ok {
		r0 = rf(name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command)
		}
	}

	return r0
}

// mockCommandMaker_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockCommandMaker_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
//   - arg ...string
func (_e *mockCommandMaker_Expecter) Execute(name interface{}, arg ...interface{}) *mockCommandMaker_Execute_Call {
	return &mockCommandMaker_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{name}, arg...)...)}
}

func (_c *mockCommandMaker_Execute_Call) Run(run func(name string, arg ...string)) *mockCommandMaker_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockCommandMaker_Execute_Call) Return(_a0 command) *mockCommandMaker_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCommandMaker_Execute_Call) RunAndReturn(run func(string, ...string) command) *mockCommandMaker_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCommandMaker creates a new instance of mockCommandMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCommandMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCommandMaker {
	mock := &mockCommandMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
