// Code generated by mockery v2.53.3. DO NOT EDIT.

package sync

import (
	context "context"

	exporter "github.com/cloudogu/ces-importer/api/exporter"
	mock "github.com/stretchr/testify/mock"
)

// mockExportDoguApiClient is an autogenerated mock type for the exportDoguApiClient type
type mockExportDoguApiClient struct {
	mock.Mock
}

type mockExportDoguApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockExportDoguApiClient) EXPECT() *mockExportDoguApiClient_Expecter {
	return &mockExportDoguApiClient_Expecter{mock: &_m.Mock}
}

// GetExportDogu provides a mock function with given fields: ctx
func (_m *mockExportDoguApiClient) GetExportDogu(ctx context.Context) (*exporter.DoguExport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExportDogu")
	}

	var r0 *exporter.DoguExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*exporter.DoguExport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *exporter.DoguExport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exporter.DoguExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExportDoguApiClient_GetExportDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportDogu'
type mockExportDoguApiClient_GetExportDogu_Call struct {
	*mock.Call
}

// GetExportDogu is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockExportDoguApiClient_Expecter) GetExportDogu(ctx interface{}) *mockExportDoguApiClient_GetExportDogu_Call {
	return &mockExportDoguApiClient_GetExportDogu_Call{Call: _e.mock.On("GetExportDogu", ctx)}
}

func (_c *mockExportDoguApiClient_GetExportDogu_Call) Run(run func(ctx context.Context)) *mockExportDoguApiClient_GetExportDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockExportDoguApiClient_GetExportDogu_Call) Return(_a0 *exporter.DoguExport, _a1 error) *mockExportDoguApiClient_GetExportDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExportDoguApiClient_GetExportDogu_Call) RunAndReturn(run func(context.Context) (*exporter.DoguExport, error)) *mockExportDoguApiClient_GetExportDogu_Call {
	_c.Call.Return(run)
	return _c
}

// SetExportDogu provides a mock function with given fields: ctx, doguName
func (_m *mockExportDoguApiClient) SetExportDogu(ctx context.Context, doguName string) (*exporter.DoguExport, error) {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for SetExportDogu")
	}

	var r0 *exporter.DoguExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*exporter.DoguExport, error)); ok {
		return rf(ctx, doguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *exporter.DoguExport); ok {
		r0 = rf(ctx, doguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exporter.DoguExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, doguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExportDoguApiClient_SetExportDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExportDogu'
type mockExportDoguApiClient_SetExportDogu_Call struct {
	*mock.Call
}

// SetExportDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *mockExportDoguApiClient_Expecter) SetExportDogu(ctx interface{}, doguName interface{}) *mockExportDoguApiClient_SetExportDogu_Call {
	return &mockExportDoguApiClient_SetExportDogu_Call{Call: _e.mock.On("SetExportDogu", ctx, doguName)}
}

func (_c *mockExportDoguApiClient_SetExportDogu_Call) Run(run func(ctx context.Context, doguName string)) *mockExportDoguApiClient_SetExportDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockExportDoguApiClient_SetExportDogu_Call) Return(_a0 *exporter.DoguExport, _a1 error) *mockExportDoguApiClient_SetExportDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExportDoguApiClient_SetExportDogu_Call) RunAndReturn(run func(context.Context, string) (*exporter.DoguExport, error)) *mockExportDoguApiClient_SetExportDogu_Call {
	_c.Call.Return(run)
	return _c
}

// newMockExportDoguApiClient creates a new instance of mockExportDoguApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockExportDoguApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockExportDoguApiClient {
	mock := &mockExportDoguApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
