// Code generated by mockery v2.53.3. DO NOT EDIT.

package sync

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockCommand is an autogenerated mock type for the command type
type mockCommand struct {
	mock.Mock
}

type mockCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCommand) EXPECT() *mockCommand_Expecter {
	return &mockCommand_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with no fields
func (_m *mockCommand) Start() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCommand_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockCommand_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *mockCommand_Expecter) Start() *mockCommand_Start_Call {
	return &mockCommand_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *mockCommand_Start_Call) Run(run func()) *mockCommand_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCommand_Start_Call) Return(_a0 error) *mockCommand_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCommand_Start_Call) RunAndReturn(run func() error) *mockCommand_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StderrPipe provides a mock function with no fields
func (_m *mockCommand) StderrPipe() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StderrPipe")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCommand_StderrPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StderrPipe'
type mockCommand_StderrPipe_Call struct {
	*mock.Call
}

// StderrPipe is a helper method to define mock.On call
func (_e *mockCommand_Expecter) StderrPipe() *mockCommand_StderrPipe_Call {
	return &mockCommand_StderrPipe_Call{Call: _e.mock.On("StderrPipe")}
}

func (_c *mockCommand_StderrPipe_Call) Run(run func()) *mockCommand_StderrPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCommand_StderrPipe_Call) Return(_a0 io.ReadCloser, _a1 error) *mockCommand_StderrPipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCommand_StderrPipe_Call) RunAndReturn(run func() (io.ReadCloser, error)) *mockCommand_StderrPipe_Call {
	_c.Call.Return(run)
	return _c
}

// StdoutPipe provides a mock function with no fields
func (_m *mockCommand) StdoutPipe() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StdoutPipe")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCommand_StdoutPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StdoutPipe'
type mockCommand_StdoutPipe_Call struct {
	*mock.Call
}

// StdoutPipe is a helper method to define mock.On call
func (_e *mockCommand_Expecter) StdoutPipe() *mockCommand_StdoutPipe_Call {
	return &mockCommand_StdoutPipe_Call{Call: _e.mock.On("StdoutPipe")}
}

func (_c *mockCommand_StdoutPipe_Call) Run(run func()) *mockCommand_StdoutPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCommand_StdoutPipe_Call) Return(_a0 io.ReadCloser, _a1 error) *mockCommand_StdoutPipe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCommand_StdoutPipe_Call) RunAndReturn(run func() (io.ReadCloser, error)) *mockCommand_StdoutPipe_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *mockCommand) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockCommand_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type mockCommand_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *mockCommand_Expecter) String() *mockCommand_String_Call {
	return &mockCommand_String_Call{Call: _e.mock.On("String")}
}

func (_c *mockCommand_String_Call) Run(run func()) *mockCommand_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCommand_String_Call) Return(_a0 string) *mockCommand_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCommand_String_Call) RunAndReturn(run func() string) *mockCommand_String_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with no fields
func (_m *mockCommand) Wait() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCommand_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type mockCommand_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *mockCommand_Expecter) Wait() *mockCommand_Wait_Call {
	return &mockCommand_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *mockCommand_Wait_Call) Run(run func()) *mockCommand_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCommand_Wait_Call) Return(_a0 error) *mockCommand_Wait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCommand_Wait_Call) RunAndReturn(run func() error) *mockCommand_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCommand creates a new instance of mockCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCommand {
	mock := &mockCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
