apiVersion: v1
values:
  images:
    cesImporter: registry.cloudogu.com/testing/ces-importer:0.0.1
patches:
  values.yaml:
    image: "{{ registryFrom .images.cesImporter }}/{{ repositoryFrom .images.cesImporter }}:{{ tagFrom .images.cesImporter }}"