apiVersion: v1
values:
  images:
    cesImporter: cloudogu/ces-importer:2.3.1
    cesImporterJob: cloudogu/ces-importer-migration-job:2.3.1
patches:
  values.yaml:
    main:
      image:
        registry: "{{ registryFrom .images.cesImporter }}"
        repository: "{{ repositoryFrom .images.cesImporter }}"
        tag: "{{ tagFrom .images.cesImporter }}"
    job:
      image:
        registry: "{{ registryFrom .images.cesImporterJob }}"
        repository: "{{ repositoryFrom .images.cesImporterJob }}"
        tag: "{{ tagFrom .images.cesImporterJob }}"
