main:
  image:
    registry: docker.io
    repository: cloudogu/ces-importer
    tag: 2.0.0
  imagePullSecrets:
    - name: "ces-container-registries"
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
job:
  image:
    registry: docker.io
    repository: cloudogu/ces-importer-migration-job
    tag: 2.0.0
  imagePullSecrets:
    - name: "ces-container-registries"
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
config:
  logging:
    # level defines the log level to be used. Valid values are: DEBUG, INFO, WARN, ERROR
    level: INFO
  api:
    # host configures the FQDN under which the exporter will be available for CES data export. The importer will
    # contact the exporter API, which returns all required data like data paths etc.
    # The exporter API endpoint is fixed and will be routed on the source side.
    host: ""
    # secretName is the name of the secret that contains the exporter API key.
    secretName: "ces-importer-secret"
    # secretDataKey contains the key name within the secret that accommodates the actual exporter API key as value.
    secretDataKey: "apiKey"
    # skipTLSVerify controls whether a client verifies the server's certificate chain and host name.
    # If skipTLSVerify is true, the client accepts any certificate presented by the server and any host name in that certificate.
    skipTLSVerify: false
    # Name of the config map containing the tls CA
    tlsConfigmapName: "ces-importer-exporter-ca"
    # Key in the configmap containing the actual tls CA value
    tlsConfigmapKey: "exporter.crt"
  ssh:
    # secretName contains the name of the secret that contains the SSH private key which the importer will use to access the source system.
    secretName: "ces-importer-secret"
    # secretDataKey contains the key name within the secret that accommodates the actual exporter SSH private key as value.
    secretDataKey: "privateKey"
  migration:
    # regularSchedule triggers recurring migration jobs while the whole source system is running.
    # Uses CRON notation like "0 2 * * *"
    regularSchedule: ""
    # finalSchedule triggers the finishing migration job while the source system is supposed to be void of active users.
    # Uses RFC 3339 notation like 2025-04-03T12:34:56Z
    finalSchedule: ""
    # changeFQDN triggers the fqdn and certificate import.
    # This is only taken into account if it is a final migration.
    # Default: false
    changeFQDN: false
    # maintenanceModeMessage is the message to been shown, when the maintenance mode gets activated at the source system.
    maintenanceModeMessage:
      # title to be shown in the maintenance mode message.
      title: "Migration in progress."
      # text to be shown in the maintenance mode message.
      text: "The migration of your instance is in progress."
    # executePreflightCheck controls whether the preflight check will be executed.
    # Default: True
    executePreflightCheck: true
  job:
    # exclude contains dogus with a pattern to exclude specific files during the import
    # example:
    #   exclude:
    #   - dogu: "official/jenkins"
    #     pattern:
    #     - "EXCLUDE_PATTERN_1"
    #     - "EXCLUDE_PATTERN_2"
    exclude: []
    # verbose sets the migrator to verbose logging
    verbose: false
  smtp:
    # The SMTP server hostname or IP address (e.g., mailhog, smtp.gmail.com)
    server: smtp.mailserver.com
    # The port the SMTP server listens on (25, 587 for TLS, 1025 for MailHog/dev)
    port: 25
    # Optional: username for SMTP authentication (leave empty if not required)
    username:
    # secretName contains the name of the secret that contains the smtp mail password which the importer will to send emails.
    secretName: "ces-importer-secret"
    # secretDataKey contains the key name that accommodates the actual exporter smtp mail password as value.
    secretDataKey: "mailPassword"
    # sender mail address
    # Email address that appears in the "From" field of the email
    from: importer@cloudogu.com
    # List of recipient email addresses
    to: []
    # useTLS configures the mail server to use TLS
    # Disable, if the mail server does not support TLS, otherwise this will lead to errors
    # default: false
    useTLS: false
    # skipTLSVerify configures the mail service to skip TLS verification when using TLS
    # default: false
    skipTLSVerify: false
    # Name of the config map containing the tls CA
    tlsConfigmapName: "ces-importer-mail-ca"
    # Key in the configmap containing the actual tls CA value
    tlsConfigmapKey: "mail.crt"
controllerManager:
  image:
    tag: 0.0.1
image:
  tag: 0.0.1
