// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	migration "github.com/cloudogu/ces-importer/migration"
	mock "github.com/stretchr/testify/mock"
)

// mockSystemInfoGetter is an autogenerated mock type for the systemInfoGetter type
type mockSystemInfoGetter struct {
	mock.Mock
}

type mockSystemInfoGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSystemInfoGetter) EXPECT() *mockSystemInfoGetter_Expecter {
	return &mockSystemInfoGetter_Expecter{mock: &_m.Mock}
}

// GetImporterSystemInfo provides a mock function with given fields: ctx
func (_m *mockSystemInfoGetter) GetImporterSystemInfo(ctx context.Context) (*migration.SystemInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImporterSystemInfo")
	}

	var r0 *migration.SystemInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*migration.SystemInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *migration.SystemInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*migration.SystemInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSystemInfoGetter_GetImporterSystemInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImporterSystemInfo'
type mockSystemInfoGetter_GetImporterSystemInfo_Call struct {
	*mock.Call
}

// GetImporterSystemInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockSystemInfoGetter_Expecter) GetImporterSystemInfo(ctx interface{}) *mockSystemInfoGetter_GetImporterSystemInfo_Call {
	return &mockSystemInfoGetter_GetImporterSystemInfo_Call{Call: _e.mock.On("GetImporterSystemInfo", ctx)}
}

func (_c *mockSystemInfoGetter_GetImporterSystemInfo_Call) Run(run func(ctx context.Context)) *mockSystemInfoGetter_GetImporterSystemInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockSystemInfoGetter_GetImporterSystemInfo_Call) Return(_a0 *migration.SystemInfo, _a1 error) *mockSystemInfoGetter_GetImporterSystemInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSystemInfoGetter_GetImporterSystemInfo_Call) RunAndReturn(run func(context.Context) (*migration.SystemInfo, error)) *mockSystemInfoGetter_GetImporterSystemInfo_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSystemInfoGetter creates a new instance of mockSystemInfoGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSystemInfoGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSystemInfoGetter {
	mock := &mockSystemInfoGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
