// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	migration "github.com/cloudogu/ces-importer/migration"
	mock "github.com/stretchr/testify/mock"
)

// mockExportDoguClient is an autogenerated mock type for the exportDoguClient type
type mockExportDoguClient struct {
	mock.Mock
}

type mockExportDoguClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockExportDoguClient) EXPECT() *mockExportDoguClient_Expecter {
	return &mockExportDoguClient_Expecter{mock: &_m.Mock}
}

// SetExportDogu provides a mock function with given fields: ctx, doguName
func (_m *mockExportDoguClient) SetExportDogu(ctx context.Context, doguName string) (*migration.DoguExport, error) {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for SetExportDogu")
	}

	var r0 *migration.DoguExport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*migration.DoguExport, error)); ok {
		return rf(ctx, doguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *migration.DoguExport); ok {
		r0 = rf(ctx, doguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*migration.DoguExport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, doguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockExportDoguClient_SetExportDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExportDogu'
type mockExportDoguClient_SetExportDogu_Call struct {
	*mock.Call
}

// SetExportDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *mockExportDoguClient_Expecter) SetExportDogu(ctx interface{}, doguName interface{}) *mockExportDoguClient_SetExportDogu_Call {
	return &mockExportDoguClient_SetExportDogu_Call{Call: _e.mock.On("SetExportDogu", ctx, doguName)}
}

func (_c *mockExportDoguClient_SetExportDogu_Call) Run(run func(ctx context.Context, doguName string)) *mockExportDoguClient_SetExportDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockExportDoguClient_SetExportDogu_Call) Return(_a0 *migration.DoguExport, _a1 error) *mockExportDoguClient_SetExportDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockExportDoguClient_SetExportDogu_Call) RunAndReturn(run func(context.Context, string) (*migration.DoguExport, error)) *mockExportDoguClient_SetExportDogu_Call {
	_c.Call.Return(run)
	return _c
}

// newMockExportDoguClient creates a new instance of mockExportDoguClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockExportDoguClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockExportDoguClient {
	mock := &mockExportDoguClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
