// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockHealthClient is an autogenerated mock type for the healthClient type
type mockHealthClient struct {
	mock.Mock
}

type mockHealthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHealthClient) EXPECT() *mockHealthClient_Expecter {
	return &mockHealthClient_Expecter{mock: &_m.Mock}
}

// GetIsHealthy provides a mock function with given fields: ctx
func (_m *mockHealthClient) GetIsHealthy(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetIsHealthy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockHealthClient_GetIsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIsHealthy'
type mockHealthClient_GetIsHealthy_Call struct {
	*mock.Call
}

// GetIsHealthy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockHealthClient_Expecter) GetIsHealthy(ctx interface{}) *mockHealthClient_GetIsHealthy_Call {
	return &mockHealthClient_GetIsHealthy_Call{Call: _e.mock.On("GetIsHealthy", ctx)}
}

func (_c *mockHealthClient_GetIsHealthy_Call) Run(run func(ctx context.Context)) *mockHealthClient_GetIsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockHealthClient_GetIsHealthy_Call) Return(_a0 bool, _a1 error) *mockHealthClient_GetIsHealthy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockHealthClient_GetIsHealthy_Call) RunAndReturn(run func(context.Context) (bool, error)) *mockHealthClient_GetIsHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHealthClient creates a new instance of mockHealthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHealthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHealthClient {
	mock := &mockHealthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
