// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	configuration "github.com/cloudogu/ces-importer/configuration"
	mock "github.com/stretchr/testify/mock"
)

// mockTestSSHConnection is an autogenerated mock type for the testSSHConnection type
type mockTestSSHConnection struct {
	mock.Mock
}

type mockTestSSHConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTestSSHConnection) EXPECT() *mockTestSSHConnection_Expecter {
	return &mockTestSSHConnection_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, cfg, secretClient2, exportDoguClient3
func (_m *mockTestSSHConnection) Execute(ctx context.Context, cfg configuration.Coordinator, secretClient2 secretClient, exportDoguClient3 exportDoguClient) error {
	ret := _m.Called(ctx, cfg, secretClient2, exportDoguClient3)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, configuration.Coordinator, secretClient, exportDoguClient) error); ok {
		r0 = rf(ctx, cfg, secretClient2, exportDoguClient3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockTestSSHConnection_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockTestSSHConnection_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg configuration.Coordinator
//   - secretClient2 secretClient
//   - exportDoguClient3 exportDoguClient
func (_e *mockTestSSHConnection_Expecter) Execute(ctx interface{}, cfg interface{}, secretClient2 interface{}, exportDoguClient3 interface{}) *mockTestSSHConnection_Execute_Call {
	return &mockTestSSHConnection_Execute_Call{Call: _e.mock.On("Execute", ctx, cfg, secretClient2, exportDoguClient3)}
}

func (_c *mockTestSSHConnection_Execute_Call) Run(run func(ctx context.Context, cfg configuration.Coordinator, secretClient2 secretClient, exportDoguClient3 exportDoguClient)) *mockTestSSHConnection_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(configuration.Coordinator), args[2].(secretClient), args[3].(exportDoguClient))
	})
	return _c
}

func (_c *mockTestSSHConnection_Execute_Call) Return(_a0 error) *mockTestSSHConnection_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTestSSHConnection_Execute_Call) RunAndReturn(run func(context.Context, configuration.Coordinator, secretClient, exportDoguClient) error) *mockTestSSHConnection_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTestSSHConnection creates a new instance of mockTestSSHConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTestSSHConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTestSSHConnection {
	mock := &mockTestSSHConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
