// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockFqdnChanger is an autogenerated mock type for the fqdnChanger type
type mockFqdnChanger struct {
	mock.Mock
}

type mockFqdnChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFqdnChanger) EXPECT() *mockFqdnChanger_Expecter {
	return &mockFqdnChanger_Expecter{mock: &_m.Mock}
}

// ChangeFQDN provides a mock function with given fields: ctx
func (_m *mockFqdnChanger) ChangeFQDN(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ChangeFQDN")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFqdnChanger_ChangeFQDN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeFQDN'
type mockFqdnChanger_ChangeFQDN_Call struct {
	*mock.Call
}

// ChangeFQDN is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockFqdnChanger_Expecter) ChangeFQDN(ctx interface{}) *mockFqdnChanger_ChangeFQDN_Call {
	return &mockFqdnChanger_ChangeFQDN_Call{Call: _e.mock.On("ChangeFQDN", ctx)}
}

func (_c *mockFqdnChanger_ChangeFQDN_Call) Run(run func(ctx context.Context)) *mockFqdnChanger_ChangeFQDN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockFqdnChanger_ChangeFQDN_Call) Return(_a0 error) *mockFqdnChanger_ChangeFQDN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFqdnChanger_ChangeFQDN_Call) RunAndReturn(run func(context.Context) error) *mockFqdnChanger_ChangeFQDN_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFqdnChanger creates a new instance of mockFqdnChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFqdnChanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFqdnChanger {
	mock := &mockFqdnChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
