// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockConfigSyncer is an autogenerated mock type for the configSyncer type
type mockConfigSyncer struct {
	mock.Mock
}

type mockConfigSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigSyncer) EXPECT() *mockConfigSyncer_Expecter {
	return &mockConfigSyncer_Expecter{mock: &_m.Mock}
}

// SyncConfig provides a mock function with given fields: ctx
func (_m *mockConfigSyncer) SyncConfig(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockConfigSyncer_SyncConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncConfig'
type mockConfigSyncer_SyncConfig_Call struct {
	*mock.Call
}

// SyncConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockConfigSyncer_Expecter) SyncConfig(ctx interface{}) *mockConfigSyncer_SyncConfig_Call {
	return &mockConfigSyncer_SyncConfig_Call{Call: _e.mock.On("SyncConfig", ctx)}
}

func (_c *mockConfigSyncer_SyncConfig_Call) Run(run func(ctx context.Context)) *mockConfigSyncer_SyncConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockConfigSyncer_SyncConfig_Call) Return(_a0 error) *mockConfigSyncer_SyncConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockConfigSyncer_SyncConfig_Call) RunAndReturn(run func(context.Context) error) *mockConfigSyncer_SyncConfig_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigSyncer creates a new instance of mockConfigSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigSyncer {
	mock := &mockConfigSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
