// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import (
	context "context"

	configuration "github.com/cloudogu/ces-importer/configuration"

	mock "github.com/stretchr/testify/mock"

	sync "github.com/cloudogu/ces-importer/sync"
)

// mockDataSyncer is an autogenerated mock type for the dataSyncer type
type mockDataSyncer struct {
	mock.Mock
}

type mockDataSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDataSyncer) EXPECT() *mockDataSyncer_Expecter {
	return &mockDataSyncer_Expecter{mock: &_m.Mock}
}

// SyncData provides a mock function with given fields: ctx, apiCli, config
func (_m *mockDataSyncer) SyncData(ctx context.Context, apiCli sync.ApiCli, config configuration.Job) error {
	ret := _m.Called(ctx, apiCli, config)

	if len(ret) == 0 {
		panic("no return value specified for SyncData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sync.ApiCli, configuration.Job) error); ok {
		r0 = rf(ctx, apiCli, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDataSyncer_SyncData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncData'
type mockDataSyncer_SyncData_Call struct {
	*mock.Call
}

// SyncData is a helper method to define mock.On call
//   - ctx context.Context
//   - apiCli sync.ApiCli
//   - config configuration.Job
func (_e *mockDataSyncer_Expecter) SyncData(ctx interface{}, apiCli interface{}, config interface{}) *mockDataSyncer_SyncData_Call {
	return &mockDataSyncer_SyncData_Call{Call: _e.mock.On("SyncData", ctx, apiCli, config)}
}

func (_c *mockDataSyncer_SyncData_Call) Run(run func(ctx context.Context, apiCli sync.ApiCli, config configuration.Job)) *mockDataSyncer_SyncData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sync.ApiCli), args[2].(configuration.Job))
	})
	return _c
}

func (_c *mockDataSyncer_SyncData_Call) Return(_a0 error) *mockDataSyncer_SyncData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDataSyncer_SyncData_Call) RunAndReturn(run func(context.Context, sync.ApiCli, configuration.Job) error) *mockDataSyncer_SyncData_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDataSyncer creates a new instance of mockDataSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDataSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDataSyncer {
	mock := &mockDataSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
