// Code generated by mockery v2.53.3. DO NOT EDIT.

package sync

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockApiCli is an autogenerated mock type for the ApiCli type
type MockApiCli struct {
	mock.Mock
}

type MockApiCli_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApiCli) EXPECT() *MockApiCli_Expecter {
	return &MockApiCli_Expecter{mock: &_m.Mock}
}

// DoGetRequest provides a mock function with given fields: ctx, exporterUrl
func (_m *MockApiCli) DoGetRequest(ctx context.Context, exporterUrl string) ([]byte, error) {
	ret := _m.Called(ctx, exporterUrl)

	if len(ret) == 0 {
		panic("no return value specified for DoGetRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, exporterUrl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, exporterUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, exporterUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiCli_DoGetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoGetRequest'
type MockApiCli_DoGetRequest_Call struct {
	*mock.Call
}

// DoGetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - exporterUrl string
func (_e *MockApiCli_Expecter) DoGetRequest(ctx interface{}, exporterUrl interface{}) *MockApiCli_DoGetRequest_Call {
	return &MockApiCli_DoGetRequest_Call{Call: _e.mock.On("DoGetRequest", ctx, exporterUrl)}
}

func (_c *MockApiCli_DoGetRequest_Call) Run(run func(ctx context.Context, exporterUrl string)) *MockApiCli_DoGetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockApiCli_DoGetRequest_Call) Return(result []byte, err error) *MockApiCli_DoGetRequest_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockApiCli_DoGetRequest_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockApiCli_DoGetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DoPostRequest provides a mock function with given fields: ctx, exporterUrl, body, pathParams
func (_m *MockApiCli) DoPostRequest(ctx context.Context, exporterUrl string, body io.Reader, pathParams []string) ([]byte, error) {
	ret := _m.Called(ctx, exporterUrl, body, pathParams)

	if len(ret) == 0 {
		panic("no return value specified for DoPostRequest")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, []string) ([]byte, error)); ok {
		return rf(ctx, exporterUrl, body, pathParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, []string) []byte); ok {
		r0 = rf(ctx, exporterUrl, body, pathParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, []string) error); ok {
		r1 = rf(ctx, exporterUrl, body, pathParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiCli_DoPostRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoPostRequest'
type MockApiCli_DoPostRequest_Call struct {
	*mock.Call
}

// DoPostRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - exporterUrl string
//   - body io.Reader
//   - pathParams []string
func (_e *MockApiCli_Expecter) DoPostRequest(ctx interface{}, exporterUrl interface{}, body interface{}, pathParams interface{}) *MockApiCli_DoPostRequest_Call {
	return &MockApiCli_DoPostRequest_Call{Call: _e.mock.On("DoPostRequest", ctx, exporterUrl, body, pathParams)}
}

func (_c *MockApiCli_DoPostRequest_Call) Run(run func(ctx context.Context, exporterUrl string, body io.Reader, pathParams []string)) *MockApiCli_DoPostRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].([]string))
	})
	return _c
}

func (_c *MockApiCli_DoPostRequest_Call) Return(result []byte, err error) *MockApiCli_DoPostRequest_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockApiCli_DoPostRequest_Call) RunAndReturn(run func(context.Context, string, io.Reader, []string) ([]byte, error)) *MockApiCli_DoPostRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApiCli creates a new instance of MockApiCli. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApiCli(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApiCli {
	mock := &MockApiCli{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
