// Code generated by mockery v2.53.3. DO NOT EDIT.

package mail

import (
	smtp "net/smtp"

	mock "github.com/stretchr/testify/mock"
)

// MockSenderService is an autogenerated mock type for the SenderService type
type MockSenderService struct {
	mock.Mock
}

type MockSenderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSenderService) EXPECT() *MockSenderService_Expecter {
	return &MockSenderService_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: addr, a, From, To, msg
func (_m *MockSenderService) Execute(addr string, a smtp.Auth, from string, to []string, msg []byte) error {
	ret := _m.Called(addr, a, from, to, msg)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, smtp.Auth, string, []string, []byte) error); ok {
		r0 = rf(addr, a, from, to, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSenderService_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSenderService_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method To define mock.On call
//   - addr string
//   - a smtp.Auth
//   - From string
//   - To []string
//   - msg []byte
func (_e *MockSenderService_Expecter) Execute(addr interface{}, a interface{}, from interface{}, to interface{}, msg interface{}) *MockSenderService_Execute_Call {
	return &MockSenderService_Execute_Call{Call: _e.mock.On("Execute", addr, a, from, to, msg)}
}

func (_c *MockSenderService_Execute_Call) Run(run func(addr string, a smtp.Auth, from string, to []string, msg []byte)) *MockSenderService_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(smtp.Auth), args[2].(string), args[3].([]string), args[4].([]byte))
	})
	return _c
}

func (_c *MockSenderService_Execute_Call) Return(_a0 error) *MockSenderService_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSenderService_Execute_Call) RunAndReturn(run func(string, smtp.Auth, string, []string, []byte) error) *MockSenderService_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSenderService creates a new instance of MockSenderService. It also registers a testing interface on the mock and a cleanup function To assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSenderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSenderService {
	mock := &MockSenderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
