// Code generated by mockery v2.53.3. DO NOT EDIT.

package mail

import (
	tls "crypto/tls"

	mock "github.com/stretchr/testify/mock"
)

// MockSMTPClientFactory is an autogenerated mock type for the SMTPClientFactory type
type MockSMTPClientFactory struct {
	mock.Mock
}

type MockSMTPClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMTPClientFactory) EXPECT() *MockSMTPClientFactory_Expecter {
	return &MockSMTPClientFactory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function with given fields: addr
func (_m *MockSMTPClientFactory) NewClient(addr string) (SMTPClient, error) {
	ret := _m.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 SMTPClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (SMTPClient, error)); ok {
		return rf(addr)
	}
	if rf, ok := ret.Get(0).(func(string) SMTPClient); ok {
		r0 = rf(addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SMTPClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSMTPClientFactory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type MockSMTPClientFactory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - addr string
func (_e *MockSMTPClientFactory_Expecter) NewClient(addr interface{}) *MockSMTPClientFactory_NewClient_Call {
	return &MockSMTPClientFactory_NewClient_Call{Call: _e.mock.On("NewClient", addr)}
}

func (_c *MockSMTPClientFactory_NewClient_Call) Run(run func(addr string)) *MockSMTPClientFactory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSMTPClientFactory_NewClient_Call) Return(_a0 SMTPClient, _a1 error) *MockSMTPClientFactory_NewClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSMTPClientFactory_NewClient_Call) RunAndReturn(run func(string) (SMTPClient, error)) *MockSMTPClientFactory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewTLSClient provides a mock function with given fields: addr, tlsConfig
func (_m *MockSMTPClientFactory) NewTLSClient(addr string, tlsConfig *tls.Config) (SMTPClient, error) {
	ret := _m.Called(addr, tlsConfig)

	if len(ret) == 0 {
		panic("no return value specified for NewTLSClient")
	}

	var r0 SMTPClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *tls.Config) (SMTPClient, error)); ok {
		return rf(addr, tlsConfig)
	}
	if rf, ok := ret.Get(0).(func(string, *tls.Config) SMTPClient); ok {
		r0 = rf(addr, tlsConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SMTPClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *tls.Config) error); ok {
		r1 = rf(addr, tlsConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSMTPClientFactory_NewTLSClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTLSClient'
type MockSMTPClientFactory_NewTLSClient_Call struct {
	*mock.Call
}

// NewTLSClient is a helper method to define mock.On call
//   - addr string
//   - tlsConfig *tls.Config
func (_e *MockSMTPClientFactory_Expecter) NewTLSClient(addr interface{}, tlsConfig interface{}) *MockSMTPClientFactory_NewTLSClient_Call {
	return &MockSMTPClientFactory_NewTLSClient_Call{Call: _e.mock.On("NewTLSClient", addr, tlsConfig)}
}

func (_c *MockSMTPClientFactory_NewTLSClient_Call) Run(run func(addr string, tlsConfig *tls.Config)) *MockSMTPClientFactory_NewTLSClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*tls.Config))
	})
	return _c
}

func (_c *MockSMTPClientFactory_NewTLSClient_Call) Return(_a0 SMTPClient, _a1 error) *MockSMTPClientFactory_NewTLSClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSMTPClientFactory_NewTLSClient_Call) RunAndReturn(run func(string, *tls.Config) (SMTPClient, error)) *MockSMTPClientFactory_NewTLSClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSMTPClientFactory creates a new instance of MockSMTPClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMTPClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMTPClientFactory {
	mock := &MockSMTPClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
