// Code generated by mockery v2.53.3. DO NOT EDIT.

package mail

import mock "github.com/stretchr/testify/mock"

// MockDialFunc is an autogenerated mock type for the DialFunc type
type MockDialFunc struct {
	mock.Mock
}

type MockDialFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDialFunc) EXPECT() *MockDialFunc_Expecter {
	return &MockDialFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: addr
func (_m *MockDialFunc) Execute(addr string) (SMTPClient, error) {
	ret := _m.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 SMTPClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (SMTPClient, error)); ok {
		return rf(addr)
	}
	if rf, ok := ret.Get(0).(func(string) SMTPClient); ok {
		r0 = rf(addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SMTPClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDialFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDialFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - addr string
func (_e *MockDialFunc_Expecter) Execute(addr interface{}) *MockDialFunc_Execute_Call {
	return &MockDialFunc_Execute_Call{Call: _e.mock.On("Execute", addr)}
}

func (_c *MockDialFunc_Execute_Call) Run(run func(addr string)) *MockDialFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDialFunc_Execute_Call) Return(_a0 SMTPClient, _a1 error) *MockDialFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDialFunc_Execute_Call) RunAndReturn(run func(string) (SMTPClient, error)) *MockDialFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDialFunc creates a new instance of MockDialFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDialFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDialFunc {
	mock := &MockDialFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
