// Code generated by mockery v2.53.3. DO NOT EDIT.

package mail

import (
	tls "crypto/tls"
	io "io"
	smtp "net/smtp"

	mock "github.com/stretchr/testify/mock"
)

// MockSMTPClient is an autogenerated mock type for the SMTPClient type
type MockSMTPClient struct {
	mock.Mock
}

type MockSMTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMTPClient) EXPECT() *MockSMTPClient_Expecter {
	return &MockSMTPClient_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function with given fields: auth
func (_m *MockSMTPClient) Auth(auth smtp.Auth) error {
	ret := _m.Called(auth)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(smtp.Auth) error); ok {
		r0 = rf(auth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSMTPClient_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type MockSMTPClient_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
//   - auth smtp.Auth
func (_e *MockSMTPClient_Expecter) Auth(auth interface{}) *MockSMTPClient_Auth_Call {
	return &MockSMTPClient_Auth_Call{Call: _e.mock.On("Auth", auth)}
}

func (_c *MockSMTPClient_Auth_Call) Run(run func(auth smtp.Auth)) *MockSMTPClient_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(smtp.Auth))
	})
	return _c
}

func (_c *MockSMTPClient_Auth_Call) Return(_a0 error) *MockSMTPClient_Auth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSMTPClient_Auth_Call) RunAndReturn(run func(smtp.Auth) error) *MockSMTPClient_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function with no fields
func (_m *MockSMTPClient) Data() (io.WriteCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 io.WriteCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.WriteCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.WriteCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSMTPClient_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockSMTPClient_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *MockSMTPClient_Expecter) Data() *MockSMTPClient_Data_Call {
	return &MockSMTPClient_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *MockSMTPClient_Data_Call) Run(run func()) *MockSMTPClient_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSMTPClient_Data_Call) Return(_a0 io.WriteCloser, _a1 error) *MockSMTPClient_Data_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSMTPClient_Data_Call) RunAndReturn(run func() (io.WriteCloser, error)) *MockSMTPClient_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Extension provides a mock function with given fields: ext
func (_m *MockSMTPClient) Extension(ext string) (bool, string) {
	ret := _m.Called(ext)

	if len(ret) == 0 {
		panic("no return value specified for Extension")
	}

	var r0 bool
	var r1 string
	if rf, ok := ret.Get(0).(func(string) (bool, string)); ok {
		return rf(ext)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(ext)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(ext)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// MockSMTPClient_Extension_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extension'
type MockSMTPClient_Extension_Call struct {
	*mock.Call
}

// Extension is a helper method to define mock.On call
//   - ext string
func (_e *MockSMTPClient_Expecter) Extension(ext interface{}) *MockSMTPClient_Extension_Call {
	return &MockSMTPClient_Extension_Call{Call: _e.mock.On("Extension", ext)}
}

func (_c *MockSMTPClient_Extension_Call) Run(run func(ext string)) *MockSMTPClient_Extension_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSMTPClient_Extension_Call) Return(_a0 bool, _a1 string) *MockSMTPClient_Extension_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSMTPClient_Extension_Call) RunAndReturn(run func(string) (bool, string)) *MockSMTPClient_Extension_Call {
	_c.Call.Return(run)
	return _c
}

// Hello provides a mock function with given fields: localName
func (_m *MockSMTPClient) Hello(localName string) error {
	ret := _m.Called(localName)

	if len(ret) == 0 {
		panic("no return value specified for Hello")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(localName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSMTPClient_Hello_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hello'
type MockSMTPClient_Hello_Call struct {
	*mock.Call
}

// Hello is a helper method to define mock.On call
//   - localName string
func (_e *MockSMTPClient_Expecter) Hello(localName interface{}) *MockSMTPClient_Hello_Call {
	return &MockSMTPClient_Hello_Call{Call: _e.mock.On("Hello", localName)}
}

func (_c *MockSMTPClient_Hello_Call) Run(run func(localName string)) *MockSMTPClient_Hello_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSMTPClient_Hello_Call) Return(_a0 error) *MockSMTPClient_Hello_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSMTPClient_Hello_Call) RunAndReturn(run func(string) error) *MockSMTPClient_Hello_Call {
	_c.Call.Return(run)
	return _c
}

// Mail provides a mock function with given fields: from
func (_m *MockSMTPClient) Mail(from string) error {
	ret := _m.Called(from)

	if len(ret) == 0 {
		panic("no return value specified for Mail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(from)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSMTPClient_Mail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mail'
type MockSMTPClient_Mail_Call struct {
	*mock.Call
}

// Mail is a helper method to define mock.On call
//   - from string
func (_e *MockSMTPClient_Expecter) Mail(from interface{}) *MockSMTPClient_Mail_Call {
	return &MockSMTPClient_Mail_Call{Call: _e.mock.On("Mail", from)}
}

func (_c *MockSMTPClient_Mail_Call) Run(run func(from string)) *MockSMTPClient_Mail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSMTPClient_Mail_Call) Return(_a0 error) *MockSMTPClient_Mail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSMTPClient_Mail_Call) RunAndReturn(run func(string) error) *MockSMTPClient_Mail_Call {
	_c.Call.Return(run)
	return _c
}

// Quit provides a mock function with no fields
func (_m *MockSMTPClient) Quit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Quit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSMTPClient_Quit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Quit'
type MockSMTPClient_Quit_Call struct {
	*mock.Call
}

// Quit is a helper method to define mock.On call
func (_e *MockSMTPClient_Expecter) Quit() *MockSMTPClient_Quit_Call {
	return &MockSMTPClient_Quit_Call{Call: _e.mock.On("Quit")}
}

func (_c *MockSMTPClient_Quit_Call) Run(run func()) *MockSMTPClient_Quit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSMTPClient_Quit_Call) Return(_a0 error) *MockSMTPClient_Quit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSMTPClient_Quit_Call) RunAndReturn(run func() error) *MockSMTPClient_Quit_Call {
	_c.Call.Return(run)
	return _c
}

// Rcpt provides a mock function with given fields: to
func (_m *MockSMTPClient) Rcpt(to string) error {
	ret := _m.Called(to)

	if len(ret) == 0 {
		panic("no return value specified for Rcpt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSMTPClient_Rcpt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rcpt'
type MockSMTPClient_Rcpt_Call struct {
	*mock.Call
}

// Rcpt is a helper method to define mock.On call
//   - to string
func (_e *MockSMTPClient_Expecter) Rcpt(to interface{}) *MockSMTPClient_Rcpt_Call {
	return &MockSMTPClient_Rcpt_Call{Call: _e.mock.On("Rcpt", to)}
}

func (_c *MockSMTPClient_Rcpt_Call) Run(run func(to string)) *MockSMTPClient_Rcpt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSMTPClient_Rcpt_Call) Return(_a0 error) *MockSMTPClient_Rcpt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSMTPClient_Rcpt_Call) RunAndReturn(run func(string) error) *MockSMTPClient_Rcpt_Call {
	_c.Call.Return(run)
	return _c
}

// StartTLS provides a mock function with given fields: config
func (_m *MockSMTPClient) StartTLS(config *tls.Config) error {
	ret := _m.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for StartTLS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*tls.Config) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSMTPClient_StartTLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTLS'
type MockSMTPClient_StartTLS_Call struct {
	*mock.Call
}

// StartTLS is a helper method to define mock.On call
//   - config *tls.Config
func (_e *MockSMTPClient_Expecter) StartTLS(config interface{}) *MockSMTPClient_StartTLS_Call {
	return &MockSMTPClient_StartTLS_Call{Call: _e.mock.On("StartTLS", config)}
}

func (_c *MockSMTPClient_StartTLS_Call) Run(run func(config *tls.Config)) *MockSMTPClient_StartTLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*tls.Config))
	})
	return _c
}

func (_c *MockSMTPClient_StartTLS_Call) Return(_a0 error) *MockSMTPClient_StartTLS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSMTPClient_StartTLS_Call) RunAndReturn(run func(*tls.Config) error) *MockSMTPClient_StartTLS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSMTPClient creates a new instance of MockSMTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMTPClient {
	mock := &MockSMTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
