// Code generated by mockery v2.53.3. DO NOT EDIT.

package mail

import mock "github.com/stretchr/testify/mock"

// MockOsReadFile is an autogenerated mock type for the OsReadFile type
type MockOsReadFile struct {
	mock.Mock
}

type MockOsReadFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOsReadFile) EXPECT() *MockOsReadFile_Expecter {
	return &MockOsReadFile_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: name
func (_m *MockOsReadFile) Execute(name string) ([]byte, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOsReadFile_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOsReadFile_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - name string
func (_e *MockOsReadFile_Expecter) Execute(name interface{}) *MockOsReadFile_Execute_Call {
	return &MockOsReadFile_Execute_Call{Call: _e.mock.On("Execute", name)}
}

func (_c *MockOsReadFile_Execute_Call) Run(run func(name string)) *MockOsReadFile_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockOsReadFile_Execute_Call) Return(_a0 []byte, _a1 error) *MockOsReadFile_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOsReadFile_Execute_Call) RunAndReturn(run func(string) ([]byte, error)) *MockOsReadFile_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOsReadFile creates a new instance of MockOsReadFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOsReadFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOsReadFile {
	mock := &MockOsReadFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
