apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ces-importer.name" . }}-config
  labels:
    {{- include "ces-importer.labels" . | nindent 4 }}
data:
  logging.yaml: |
  {{- toYaml .Values.config.logging | nindent 4 }}

  api.yaml: |
    apiKey: "${API_KEY}"
    {{- toYaml .Values.config.api | nindent 4 }}

  migration.yaml: |
  {{- toYaml .Values.config.migration | nindent 4 }}

  ssh.yaml: |
    user: "root"
    privateKeyPath: "/.ssh/privateKey"
    {{- toYaml .Values.config.ssh | nindent 4 }}

  job.yaml: |
    doguVolumeBasePath: "/data"
    {{- toYaml .Values.config.job | nindent 4 }}

  job-container.yaml: |
    jobConfigMap: {{ include "job-config.name" . | quote }}
    jobServiceAccount: {{ include "ces-importer.name" . }}-main-manager
    {{- toYaml .Values.job | nindent 4 }}

  smtp.yaml: |
  {{- toYaml .Values.config.smtp | nindent 4 }}
