apiVersion: v1
kind: ConfigMap
metadata:
  name: ces-importer-config
data:
  log_level: "{{.Values.config.log_level}}"
  exporter_host: "{{.Values.config.exporter_host}}"
  exporter_port: "{{.Values.config.exporter_port}}"
  exporter_ssh_user: "{{.Values.config.exporter_ssh_user}}"
  exporter_source: "{{.Values.config.exporter_source}}"
  importer_private_ssh_key_path: "{{.Values.config.importer_private_ssh_key_path}}/{{.Values.config.importer_private_ssh_key_file_name}}"
  importer_destination: "{{.Values.config.importer_destination}}"
