apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ces-importer.name" . }}
  labels:
  {{- include "ces-importer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "ces-importer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "ces-importer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.main.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "ces-importer.name" . }}-config
        - name: migration-log
          emptyDir: {}
        - name: exporter-ca
          configMap:
            name: {{ .Values.config.api.tlsConfigmapName }}
            optional: true
        - name: mail-ca
          configMap:
            name: {{ .Values.config.smtp.tlsConfigmapName }}
            optional: true
      containers:
        - env:
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.smtp.secretName }}
                  key: {{ .Values.config.smtp.secretDataKey }}
                  optional: true
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.api.secretName }}
                  key: {{ .Values.config.api.secretDataKey }}
            - name: IMPORTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_PATH
              value: "/etc/{{ include "ces-importer.name" . }}/config"
          volumeMounts:
            - mountPath: "/etc/{{ include "ces-importer.name" . }}/config"
              name: config-volume
              readOnly: true
            - mountPath: /home/ces-importer/migration-log
              name: migration-log
            - mountPath: /etc/custom-certs/exporter
              name: exporter-ca
              readOnly: true
            - mountPath: /etc/custom-certs/mail
              name: mail-ca
              readOnly: true
          image: "{{ .Values.main.image.registry }}/{{ .Values.main.image.repository }}:{{ .Values.main.image.tag }}"
          imagePullPolicy: {{ .Values.main.imagePullPolicy | default "IfNotPresent" }}
          name: main
          resources:
            limits:
              {{- toYaml .Values.main.resources.limits | nindent 14}}
            requests:
              {{- toYaml .Values.main.resources.requests | nindent 14}}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ include "ces-importer.name" . }}-main-manager