apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ces-importer.name" . }}
  labels:
  {{- include "ces-importer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "ces-importer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "ces-importer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.main.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: exporter-ssh-private-key-volume
          secret:
            secretName: "{{ .Values.config.importer.sshSecretName}}"
        - name: migration-log
          emptyDir: {}
      containers:
        - env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ces-importer.name" . }}-config
                  key: log_level
            - name: EXPORTER_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ces-importer.name" . }}-config
                  key: exporter_host
            - name: EXPORTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.exporter.apiSecretName }}
                  key: {{ .Values.config.exporter.apiSecretDataKey }}
            - name: EXPORTER_SSH_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ces-importer.name" . }}-config
                  key: exporter_ssh_user
            - name: MIGRATION_REGULAR_SCHEDULE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ces-importer.name" . }}-config
                  key: migration_regular_schedule
            - name: MIGRATION_FINAL_SCHEDULE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ces-importer.name" . }}-config
                  key: migration_final_schedule
            - name: IMPORTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SMTP_SERVER
              value: {{ .Values.config.smtp.server | quote }}
            - name: SMTP_PORT
              value: {{ .Values.config.smtp.port | quote }}
            - name: SMTP_USERNAME
              value: {{ .Values.config.smtp.username | quote }}
            - name: SMTP_PASSWORD
              value: {{ .Values.config.smtp.password | quote }}
            - name: SMTP_FROM
              value: {{ .Values.config.smtp.from | quote }}
            - name: SMTP_TO
              value: {{ join "," .Values.config.smtp.to | quote }}
          volumeMounts:
            - name: exporter-ssh-private-key-volume
              readOnly: true
              mountPath: "{{ include "ces-importer.sshPrivateKeyPath" . }}"
            - mountPath: /home/ces-importer/migration-log
              name: migration-log
          image: "{{ .Values.main.image.registry }}/{{ .Values.main.image.repository }}:{{ .Values.main.image.tag }}"
          imagePullPolicy: {{ .Values.main.imagePullPolicy | default "IfNotPresent" }}
          name: main
          resources:
            limits:
              {{- toYaml .Values.main.resources.limits | nindent 14}}
            requests:
              {{- toYaml .Values.main.resources.requests | nindent 14}}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ include "ces-importer.name" . }}-main-manager