apiVersion: batch/v1
kind: Job
metadata:
  name: ces-importer
spec:
  template:
    spec:
      volumes:
        - name: private-key-volume
          secret:
            secretName: ces-importer-secret
      containers:
        - name: ces-importer
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: log_level
                  name: ces-importer-config
            - name: EXPORTER_HOST
              valueFrom:
                configMapKeyRef:
                  key: exporter_host
                  name: ces-importer-config
            - name: EXPORTER_PORT
              valueFrom:
                configMapKeyRef:
                  key: exporter_port
                  name: ces-importer-config
            - name: EXPORTER_SSH_USER
              valueFrom:
                configMapKeyRef:
                  key: exporter_ssh_user
                  name: ces-importer-config
            - name: EXPORTER_SOURCE
              valueFrom:
                configMapKeyRef:
                  key: exporter_source
                  name: ces-importer-config
            - name: IMPORTER_PRIVATE_SSH_KEY_PATH
              valueFrom:
                configMapKeyRef:
                  key: importer_private_ssh_key_path
                  name: ces-importer-config
            - name: IMPORTER_DESTINATION
              valueFrom:
                configMapKeyRef:
                  key: importer_destination
                  name: ces-importer-config
          volumeMounts:
            - name: private-key-volume
              readOnly: true
              mountPath: "{{.Values.config.importer_private_ssh_key_path}}"
      restartPolicy: Never
  backoffLimit: 0