// Code generated by mockery v2.53.3. DO NOT EDIT.

package configuration

import mock "github.com/stretchr/testify/mock"

// MockConfigTypes is an autogenerated mock type for the ConfigTypes type
type MockConfigTypes struct {
	mock.Mock
}

type MockConfigTypes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigTypes) EXPECT() *MockConfigTypes_Expecter {
	return &MockConfigTypes_Expecter{mock: &_m.Mock}
}

// NewMockConfigTypes creates a new instance of MockConfigTypes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigTypes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigTypes {
	mock := &MockConfigTypes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
